### ISSUE TITLE
Storing Arbitrary values in state

### ISSUE THREAD

**Issue by vibe** [hashicorp/terraform-cdk#1053] opened 2021-09-21 08:36 UTC
Is it possible to store arbitrary values in terraform state? 

I build a lot of custom resources, and my uses cases in lower level constructs are starting to require custom state to be tracked. 

For example, when generating a hash of sorts, and I would like be able to store/read the value from terraform state, so I can act on it in future `synth` steps.

The ask is similar to the functionality NullDataSource provides however NullDataSource does not persist values into state and refreshes immediately every single synth/plan.

NullProvider is also close in functionality however, triggers run during `deploy`/`apply` rather than during synth.

`setContext` and `tryGetContext` also work in a similar vain however you can also set context before any children are created in the tree, and it does not persist between synths/applys.

Here is some pseudo code to showcase what I'm aiming for.  

```typescript
class CustomConstruct extends Resource {
 constructor(scope, id) {
  super(scope, id)
  
  const existingHash = this.tryGetState("someCachingHashForExample")
  const currentHash = calculateMagicHash()

  if(existingHash !== currentHash) {
     console.log('Run some magic during synth');
  }
 }
}
``` 

I have a current work around where I basically have a cache file saved directly to `cdk.out` which is then read during synth. HOWEVER, the downside of this is the cache may not exist at all times for varies reasons. `cdk.out` is deleted, CI/CD running on a fresh container, etc, which leads me to the reasoning that I should store it in the terraform state file, since remote state will always be refreshed before any synth/apply.

Before creating this issue, I did my due diligence, I have searched the terraform documentation for HCL specific solutions to no avail and I have tunneled my way through the cdktf source code to no avail, however forgive me if there's already a primitive for this but if there is I can not seem to track this down.

**Comment by skorfmann** [comment] 2021-09-21 09:15
> I build a lot of custom resources, and my uses cases in lower level constructs are starting to require custom state to be tracked.
> 
> For example, when generating a hash of sorts, and I would like be able to store/read the value from terraform state, so I can act on it in future `synth` steps.

Reaching for Terraform state during `synth` seems a bit like breaking the boundaries between the different phases. At least by default, `synth` doesn't require any credentials or needs any knowledge about the Terraform context it'll be executed in at some point.

The `synth` process is working around the general problem by generating predictable hashes (i.e. the resource names). Assets are working (should be at least) in a similar fashion. Like, when a file wasn't touched, it shouldn't be re-processed or re-uploaded again.

> `setContext` and `tryGetContext` also work in a similar vain however you can also set context before any children are created in the tree, and it does not persist between synths/applys.

You could provide this as static context via `cdktf.json`, would this help here?

### At a more general level

Would you be able to give a concrete example of the data you wanna store here? Are we talking about hashes of files, arbitrary strings or something else?

**Comment by vibe** [comment] 2021-09-21 09:48
Hmm, crossing boundaries between different phases is definitely not ideal, I hadn't thought about it that way. 

> You could provide this as static context via cdktf.json, would this help here?

I am not sure I follow, are you suggesting I pass in values in the cdktf.json root file? 
Probably not what I'm looking for. 

> Would you be able to give a concrete example of the data you wanna store here? Are we talking about hashes of files, arbitrary strings or something else?

There's a handful of uses cases, hashes of files is definitely one of them.

For example a construct that builds a python, typescript, or any project that requires a build step for that matter, or determining whether a docker container  that does some bootstrapping should run. Ideally, the synth step could build the source files, calculate a hash for the source files, build artifacts are stored in `cdk.out` that way in the deploy step they are not required to be built, or during future synths they are not built unless the source changes. This way you can essentially store cdk.out as an entire artifact that can be deployed at will without the rest of the source code or the need to build code. 

This is just one of the uses cases. I already accomplish this with the workaround I mentioned, just trying to keep it as consistent as possible without too many rebuilds.

**Comment by skorfmann** [comment] 2021-09-21 10:23
> > You could provide this as static context via cdktf.json, would this help here?
> 
> I am not sure I follow, are you suggesting I pass in values in the cdktf.json root file?
> Probably not what I'm looking for.

Yes, that would be an option for static data. The AWS CDK is using this approach for data like Route53 Zones (in Terraform there are DataSources to get such data of course).

> For example a construct that builds a python, typescript, or any project that requires a build step for that matter, or determining whether a docker container that does some bootstrapping should run. Ideally, the synth step could build the source files, calculate a hash for the source files, build artifacts are stored in `cdk.out` that way in the deploy step they are not required to be built, or during future synths they are not built unless the source changes. This way you can essentially store cdk.out as an entire artifact that can be deployed at will without the rest of the source code or the need to build code.
> 
> This is just one of the uses cases. I already accomplish this with the workaround I mentioned, just trying to keep it as consistent as possible without always having to run potentially expensive computation.

At least dealing with Python, Typescript or Docker are essentially use-cases which can be covered by [Assets](https://github.com/hashicorp/terraform-cdk/blob/0c7464e852ca071c52075469cd1d4bbe38c17fd9/docs/working-with-cdk-for-terraform/terraform-assets.md). The hard part is of course the caching, as in to not run these steps at all if not necessary. In my personal projects, I've been ignoring this for the most part. Have extracted common tasks into these experimental packages ([Docker](https://github.com/cdktf-plus/cdktf-plus/blob/8f9f7b81708e63c9028427191e63612c36c92202/packages/%40cdktf-plus/core/lib/docker-asset/docker-asset.ts) and [NodejsFunction](https://github.com/cdktf-plus/cdktf-plus/blob/8f9f7b81708e63c9028427191e63612c36c92202/packages/%40cdktf-plus/aws/lib/nodejs-function/index.ts)). Docker itself has caching implemented itself and for Typescript [esbuild](https://esbuild.github.io/) is usually so fast that caching becomes almost neglectable. When it comes to Python, I'm not sure what needs to be done there for inline processing.

Having said that, I think there's room for improvement to deal with asset caching. Looking at what the AWS CDK folks are doing, they have a dedicated Asset Manifest, which helps to keep track of the required information to decide if assets need to be reprocessed or not. 

Would a concept like this help in your case? Out of curiosity, how large are the build times you're trying to get rid of with caching?

**Comment by vibe** [comment] 2021-09-21 10:54
I have very similar package abstractions NodeJsFunction, Docker, PoetryFunction, StaticSite, NextJSLambda, etc, etc. 

Build times vary between projects, with no cache some projects run ~10 minutes. Due to building, zipping up, running tests, etc, others run 3-5 minutes depending on the stack. 

That being said I've optimized the CI/CD environment to handle the caching aspect of it, but of course would be awesome if we maintained an asset manifest. With caching enabled, if I only make a change to a cloud resource and no source code logic it could be done within a minute, sometimes less. 

Maybe I'm overthinking the amount of performance we can squeeze out of our environments, it's definitely a nice to have but minutes add up fast if you're deploying often.

**Comment by xiehan** [comment] 2023-06-01 16:57
This is a very old ticket and CDKTF has evolved a lot since this was written so I'm going to go ahead and close this - especially since as far as I can tell the title isn't actually reflective of the feature being requested.

It's entirely possible the problem isn't actually solved yet, in which case you're welcome to create a new ticket. From reading the past discussion, it seems like #2720 might be related to what's really being asked here - the team has put that work on hold for a bit since the solution wasn't working, but we do plan to come back to it.

**Closed by xiehan** 2023-06-01 16:57 UTC
Labels: enhancement, needs-research, priority/important-soon, size/medium
