### ISSUE TITLE
Module Outputs are typed as string

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#787] opened 2021-06-18 17:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- CDKTF 0.4.0

### Affected Resource(s)

- Generated Modules

### Expected Behavior

Outputs generate types according to their Terraform Data Type

### Actual Behavior

Every Output is typed as string

### Steps to Reproduce

Add a module with diverse outputs to your cdktf.json and run `cdktf get`

### Important Factoids

- Current Code Generation: https://github.com/hashicorp/terraform-cdk/blob/main/packages/cdktf-cli/lib/get/generator/module-generator.ts#L79-L81

**Comment by jsteinich** [comment] 2021-06-18 19:21
Duplicate of #287

**Closed by jsteinich** 2021-06-18 19:21 UTC
Labels: bug, new
