### ISSUE TITLE
jsii dependency update led to cluttered tmp directory

### ISSUE THREAD

**Issue by jdiebold** [hashicorp/terraform-cdk#562] opened 2021-02-12 16:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.1.0
python 3.7

### Expected Behavior

no change of behavior with unchanged cdktf version

### Actual Behavior

jsii got updated from 1.17.1 to 1.20 (latest) on a new deployment and led to the tmp directory being cluttered with jsii-kernel  directories until the machine ran out of disk space. Probably because of https://github.com/aws/jsii/issues/700

### References
https://github.com/aws/jsii/issues/700

**Comment by skorfmann** [comment] 2021-02-12 20:23
Thanks for reporting it. 

How long did it take to fill up the disk space and how much disk space are we talking about? Just a single run or over a longer period? I'm just wondering how to reproduce it.

**Comment by jdiebold** [comment] 2021-03-19 15:53
I don't really know, but our Pods don't have a lot of disk space, i think ~10gb (and we cannot increase it) and it took a longer period (roughly 5 hours) and several runs.

**Comment by xiehan** [comment] 2023-06-01 18:41
Since this issue is well over 2 years old and both JSII and CDKTF have evolved a lot since then, I'm going to go ahead and close this. If you're still encountering problems, please go ahead and create a new issue.

**Closed by xiehan** 2023-06-01 18:41 UTC
Labels: bug, upstream/jsii, priority/important-longterm, size/large
