### ISSUE TITLE
CDK Constructs generation failure

### ISSUE THREAD

**Issue by jia3apb** [hashicorp/terraform-cdk#668] opened 2021-04-30 18:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
{
  "language": "python",
  "app": "pipenv run python main.py",
  "terraformProviders": [
    "phillbaker/elasticsearch"
  ],
  "codeMakerOutput": "imports"
}
```
```
cdktf --version
0.3.0
```
Provider: https://registry.terraform.io/providers/phillbaker/elasticsearch/latest

### Debug Output

https://gist.github.com/jia3apb/1140978f5eb440055d13f0423a31c6b3

### Expected Behavior

**cdktf get** should generate CDK Constructs for Terraform providers and module

### Actual Behavior

Fails with the error **Compilation errors prevented the JSII assembly from being created**

### Steps to Reproduce

`cdktf get`

### References

* #0000

**Comment by jsteinich** [comment] 2021-05-03 03:02
Looks to be a duplicate of #547.

**Comment by skorfmann** [comment] 2021-05-03 07:40
> Looks to be a duplicate of #547.

Thanks for referencing, gonna close this one here and prioritized #547

**Closed by skorfmann** 2021-05-03 07:40 UTC
Labels: bug, duplicate, v0.3
