### ISSUE TITLE
`cdktf-cli`: `init` always using Terraform Cloud

### ISSUE THREAD

**Issue by lohrm-stabl** [hashicorp/terraform-cdk#2960] opened 2023-06-23 12:33 UTC
### Expected Behavior

Terraform cloud is not used when entering `n` when asked for the Terraform Cloud integration.

### Actual Behavior

The web-browser opens to authenticate with Terraform Cloud.

This is the output, when entering 'n' when asked for TF cloud. I never entered 'Y', 'y', 'yes'.
```bash
❯ cdktf init
Welcome to CDK for Terraform!

By default, cdktf allows you to manage the state of your stacks using Terraform Cloud for free.
cdktf will request an API token for app.terraform.io using your browser.

If login is successful, cdktf will store the token in plain text in
the following file for use by subsequent Terraform commands:
    /home/michi/.terraform.d/credentials.tfrc.json

Note: The local storage mode isn't recommended for storing the state of your stacks.

? Do you want to continue with Terraform Cloud remote state management? yes

opening webpage using your browser.....

If the web browser didn't open the window automatically, you can go to the following url:
        https://app.terraform.io/app/settings/tokens?source=terraform-login

? Token for app.terraform.io 🔑
```

Or when piping `n` into `cdktf`:
```bash
❯ echo 'n' | cdktf init
Welcome to CDK for Terraform!

By default, cdktf allows you to manage the state of your stacks using Terraform Cloud for free.
cdktf will request an API token for app.terraform.io using your browser.

If login is successful, cdktf will store the token in plain text in
the following file for use by subsequent Terraform commands:
    /home/michi/.terraform.d/credentials.tfrc.json

Note: The local storage mode isn't recommended for storing the state of your stacks.

? Do you want to continue with Terraform Cloud remote state management? yes

opening webpage using your browser.....

If the web browser didn't open the window automatically, you can go to the following url:
        https://app.terraform.io/app/settings/tokens?source=terraform-login

? Token for app.terraform.io 🔑 %
```

### Steps to Reproduce

1. Install Terraform
2. Run `npm install cdktf-cli`
3. Run `cdktf init`
4. When asked for TF cloud, enter ``n`
5. Webbrowser opens anyways

### Versions

language: null
cdktf-cli: 0.17.0
node: v20.3.1
terraform: 1.5.1
arch: x64
os: linux 5.15.90.1-microsoft-standard-WSL2

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment] 2023-06-23 12:40
Hi @lohrm-stabl 👋

thank you for reporting this! I'll close this as it's a duplicate of https://github.com/hashicorp/terraform-cdk/issues/2952

**Closed by ansgarm** 2023-06-23 12:40 UTC
Labels: bug, new
