### ISSUE TITLE
Overprivileged admin user is required to run cdktf diff and deploy on Terraform Cloud

### ISSUE THREAD

**Issue by daniel-laszlo** [hashicorp/terraform-cdk#2236] opened 2022-10-31 15:18 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.13.2
Terraform Cloud

### Affected Resource(s)

`cdktf diff`
`cdktf deploy`

as both commands use json-output endpoint where [You must access it with a user token or team token that has admin level access to the workspace.](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/plans#retrieve-the-json-execution-plan)

### Debug Output

```
$ cdktf diff
STACK  Creating Terraform Cloud configuration version
STACK  Created Terraform Cloud configuration version cv-XXXXXXXXXXXXXXXX
STACK  Zipping up the directory cdktf.out/stacks/STACK
STACK  Uploading the directory to Terraform Cloud
STACK  Uploaded the directory to Terraform Cloud
STACK  Waiting for configuration version to become ready...
STACK  Creating speculative Terraform Cloud run
STACK  Created speculative Terraform Cloud run: https://app.terraform.io/app/ORGANIZATION/workspaces/WORKSPACE/runs/run-XXXXXXXXXXXXXXXX
STACK  Speculative Terraform Cloud run done
STACK  Getting plan output
[2022-10-17T15:03:30.423] [ERROR] default - Error in Plan: {"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n    at qqe.exports (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:151:8020)\n    at Lqe.exports (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:151:8198)\n    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:152:8212)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"url":"/plans/plan-XXXXXXXXXXXXXXXX/json-output","method":"get","headers":{"Authorization":"Bearer TOKEN","Accept":"application/json","Content-Type":"application/vnd.api+json","User-Agent":"terraform-cloud/1.15.0"},"baseURL":"https://app.terraform.io/api/v2","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}
⠙  Processing
External Error: Stack failed to plan: STACK. Please check the logs for more information.
```

### Expected Behavior

`cdktf diff` should be allowed with plan permission in TFC
`cdktf deploy` should be allowed with write permission in TFC
Highly privileged admin role should not be required to run any cdktf command.

### Actual Behavior

cdktf throws `{ "status": "404", "title": "not found"}` error for `/json-output` when ran with lesser privileged role.

**Comment by daniel-laszlo** [comment] 2022-11-10 10:19
https://github.com/hashicorp/terraform-cdk/pull/2258 will make the issue more explicit but won't solve it. Can we keep this issue open until it is solved please?

**Comment by mutahhir** [comment] 2022-11-10 10:50
@daniel-laszlo Can you provide some more detail on how #2258 doesn't solve it?

I also think I've also not provided enough information about what the PR above does, so I'll try to get into a bit more detail here:

- The problem with `json-output` without an admin token is that it caused the planning to (appear to) fail. The PR now gracefully falls back, informs the user, and just gets the plan information and uses that to proceed (we need the information in the `json-output` or `plan/:id` to see if the plan has changes that need applying).
- The PR also adds more checks to apply, and getting the state information, and gracefully handles when the requester doesn't have the right permissions.

**Comment by daniel-laszlo** [comment] 2022-11-10 10:54
The expected behavior is the same as what is with Terraform CLI:
- cdktf diff should be allowed with plan permission in TFC
- cdktf deploy should be allowed with write permission in TFC
Admin permission should not be required to use the cdktf cli.

**Comment by mutahhir** [comment] 2022-11-10 11:05
> The expected behavior is the same as what is with Terraform CLI:
> 
> * cdktf diff should be allowed with plan permission in TFC
> * cdktf deploy should be allowed with write permission in TFC
>   Admin permission should not be required to use the cdktf cli.

I wonder if I'm missing something, but all the above should be true now. It's also true that we'll _try_ to get `json-output` which requires admin token, but it doesn't prevent anything anymore.

**Comment by mutahhir** [comment] 2022-11-10 11:16
One caveat to the above is that without `json-output` we no longer have the ability to display the plan anymore, and you'll have to use the plan link (that will be output on the terminal) to view the changes. 

This won't be blocking anymore, so closing the issue is fine imo, however, it's a degradation of user experience, and is definitely inconvenient. That's something we'll fix in time as we look into using the Terraform CLI as the backend.

**Comment by daniel-laszlo** [comment] 2022-11-11 09:17
Ah ok, makes sense. Thank you for the explanation 👍

**Closed** 2022-11-17 20:09 UTC
Labels: bug, terraform cloud, priority/important-soon, size/medium
