### ISSUE TITLE
cdktf get not working within node:apline docker container

### ISSUE THREAD

**Issue by nadworny** [hashicorp/terraform-cdk#1100] opened 2021-09-29 14:10 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf 0.6.3 & python 3.8

### Affected Resource(s)
`cdktf`

### Debug Output
https://gist.github.com/nadworny/92bceb4a75ec6ad331319eab12bd60e3

### Expected Behavior
Project is properly setup using `cdktf get`.

### Actual Behavior
`cdktf get` is throwing an error. It doesn't work with 0.6.1, 0.6.2 & 0.6.3 but it works with 0.5.0.

### Steps to Reproduce
1. Dockerfile
```Dockerfile
FROM node:alpine

RUN npm install --global cdktf-cli@0.6.3

ENV DEFAULT_TERRAFORM_VERSION=1.0.7

# Install Terraform
RUN apk add --update --no-cache git curl docker-cli unzip python3 python3-dev && \
    ln -sf python3 /usr/bin/python && python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools==45 && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    AVAILABLE_TERRAFORM_VERSIONS="0.15.0 ${DEFAULT_TERRAFORM_VERSION}" && \
    for VERSION in ${AVAILABLE_TERRAFORM_VERSIONS}; do curl -LOk https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip && \
    mkdir -p /usr/local/bin/tf/versions/${VERSION} && \
    unzip terraform_${VERSION}_linux_amd64.zip -d /usr/local/bin/tf/versions/${VERSION} && \
    ln -s /usr/local/bin/tf/versions/${VERSION}/terraform /usr/local/bin/terraform${VERSION};rm terraform_${VERSION}_linux_amd64.zip;done && \
    ln -s /usr/local/bin/tf/versions/${DEFAULT_TERRAFORM_VERSION}/terraform /usr/local/bin/terraform

WORKDIR /cdktf
COPY cdktf.json .
RUN cdktf get
```
2. Example cdktf.json
```
{
  "language": "python",
  "app": "poetry run poe run",
  "terraformProviders": [
    "hashicorp/azurerm@>= 2.0"
  ],
  "terraformModules": [],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```
3. Build docker image
```shell
docker build -t cdktf -f Dockerfile .
```

**Comment by nadworny** [comment] 2021-09-29 14:13
Just saw similar issue https://github.com/hashicorp/terraform-cdk/issues/1098

**Comment by jsteinich** [comment] 2021-09-30 02:56
Going to close this in favor of #1098 which narrows down what the problem is and has a workaround.

**Closed by jsteinich** 2021-09-30 02:56 UTC
Labels: bug, new
