### ISSUE TITLE
Generating azurerm provider for go exceeds 'hard' memory limit

### ISSUE THREAD

**Issue by waxb** [hashicorp/terraform-cdk#1264] opened 2021-11-05 16:26 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
waxb@mbp:cdktf-azure-go$ cdktf --version
0.7.0
waxb@mbp:cdktf-azure-go$ cat cdktf.json 
{
    "language": "go",
    "app": "go run main.go",
    "codeMakerOutput": "generated",
    "terraformProviders": ["hashicorp/azurerm@~> 2.74"],
    "terraformModules": [],
    "context": {
        "excludeStackIdFromLogicalIds": "true",
	"allowSepCharsInLogicalIds": "true"
    }
}
waxb@mbp:cdktf-azure-go$ go version
go version go1.17.2 darwin/amd64
```

### Expected Behavior
```
waxb@mbp:cdktf-azure-go$ cdktf get
⠧ downloading and generating modules and providers...
Generated go constructs in the output directory: generated

The generated code depends on jsii-runtime-go. If you haven't yet installed it, you can run go mod tidy to automatically install it.
waxb@mbp:cdktf-azure-go$ 
```
### Actual Behavior

https://gist.github.com/waxb/78ecff27cd265525e290043da7db6c71

```
  | <--- Last few GCs --->
  | [49924:0x7f8761900000]   197321 ms: Mark-sweep 10085.5 (10275.2) -> 10071.7 (10276.9) MB, 12795.4 / 0.0 ms  (average mu = 0.142, current mu = 0.002) allocation failure scavenge might not succeed
  | [49924:0x7f8761900000]   210142 ms: Mark-sweep 10087.5 (10276.9) -> 10073.8 (10279.2) MB, 12795.8 / 0.0 ms  (average mu = 0.077, current mu = 0.002) allocation failure scavenge might not succeed
  | <--- JS stacktrace --->
  | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

`cdktf get` fails as the azurerm provider generation is bigger than the default
(`console.warn(found NODE_OPTIONS environment variable without a setting for --max-old-space-size.
The provider generation needs a substantial amount of memory (~13GB) for some providers and languages.
So cdktf-cli sets it to NODE_OPTIONS="--max-old-space-size=16384" by default. As your environment already contains
a NODE_OPTIONS variable, we won't override it. Hence, the provider generation might fail with an out of memory error.);` )

### Important Factoids

⚠️ Note: be sure you are using underscores instead of dashes as seen in the example, not in the warn message
workaround: `export NODE_OPTIONS=--max_old_space_size=16384` as azurerm takes ~13 GBs to generate

The workaround is only working if you are seeing the `...NODE_OPTIONS variable, we won't override it...` message as shown above.

### References

[This](https://github.com/hashicorp/terraform-cdk/blob/36e350bf840bd55a908aea566842105abc6be553/packages/%40cdktf/provider-generator/lib/get/constructs-maker.ts#L319) seems to be the affecting line

I got the idea from [here](https://github.com/aws/jsii/issues/745)

**Comment by ansgarm** [comment] 2021-11-05 20:57
Hi @waxb!
Thank you for reporting the issue. We're currently setting the limit to 10GB because the default is only something along the lines of 2GB 😅 Interesting that the `azurerm` provider needs even more – in the past usually the AWS provider popped up with this issue.

I fear that this is something we should fix upstream in JSII as we're now approaching memory requirements that I'd rather not want to require from users. Fixing the root cause here sounds more reasonable to me.

**Comment by ansgarm** [comment] 2021-11-05 21:00
Just a guess (to be confirmed): The memory usage could be a side effect of https://github.com/aws/jsii/issues/3091

**Comment by edmundloo** [comment] 2021-11-06 01:30
I wanted to add that I am also getting the same error trying to get the aws provider on my local machine:


```
❯ NODE_OPTIONS="--max-old-space-size=20480" cdktf get                                          
NOTE: Temp directory retained due to an error: /tmp/temp-E2uxUG
Error: jsii compilation failed with non-zero exit code: 134
  | <--- Last few GCs --->
  | [13402:0x5e38f60]   792096 ms: Mark-sweep 10092.1 (10282.1) -> 10078.4 (10284.4) MB, 7205.0 / 0.0 ms  (average mu = 0.140, current mu = 0.005) allocation failure scavenge might not succeed
  | [13402:0x5e38f60]   799387 ms: Mark-sweep 10094.3 (10284.4) -> 10078.9 (10284.9) MB, 7258.6 / 0.0 ms  (average mu = 0.077, current mu = 0.004) allocation failure scavenge might not succeed
  | <--- JS stacktrace --->
  | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
  |  1: 0xb21900 node::Abort() [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  |  2: 0xa361fc node::FatalError(char const*, char const*) [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  |  3: 0xd1021e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  |  4: 0xd10597 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  |  5: 0xec8555  [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  |  6: 0xec9036  [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  |  7: 0xed8dbe  [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  |  8: 0xed9810 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  |  9: 0xedc7be v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  | 10: 0xe9ddaa v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  | 11: 0x121b418 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  | 12: 0x160f479  [/home/edmund/.nvm/versions/node/v17.0.1/bin/node]
  | Aborted (core dumped)
  +----------------------------------------------------------------------------------
  | Command: /home/edmund/.nvm/versions/node/v17.0.1/lib/node_modules/cdktf-cli/node_modules/jsii-pacmak/bin/jsii-pacmak --code-only
  | Workdir: /tmp/temp-E2uxUG
  +----------------------------------------------------------------------------------
    at newError (/home/edmund/.nvm/versions/node/v17.0.1/lib/node_modules/cdktf-cli/node_modules/@skorfmann/jsii-srcmak/lib/util.js:58:20)
    at ChildProcess.<anonymous> (/home/edmund/.nvm/versions/node/v17.0.1/lib/node_modules/cdktf-cli/node_modules/@skorfmann/jsii-srcmak/lib/util.js:75:29)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

This is my `cdktf.json`:
```
{
  "language": "go",
  "app": "go run main.go",
  "codeMakerOutput": "generated",
  "projectId": "99dcb13a-4cf7-4cc7-9a60-17d5d717eb07",
  "terraformProviders": ["hashicorp/aws@~> 3.63"],
  "terraformModules": [],
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```

**Comment by ansgarm** [comment] 2021-11-08 09:36
> Just a guess (to be confirmed): The memory usage could be a side effect of [aws/jsii#3091](https://github.com/aws/jsii/issues/3091)

Could not confirm this – it still failed with an OOM error after commenting out that cpu heavy code.

**Comment by jcdan3** [comment] 2021-11-09 00:02
I am getting the same error but with the provider `"hashicorp/aws@~> 3.64.2"`.
Setting `export NODE_OPTIONS="--max_old_space_size=20384"` did not work on my side.

The output is:
` | <--- Last few GCs --->
  | [933216:0x54d70a0]   397793 ms: Mark-sweep 10091.3 (10282.0) -> 10079.4 (10286.0) MB, 6808.6 / 0.0 ms  (average mu = 0.081, current mu = 0.002) allocation failure scavenge might not succeed
  | [933216:0x54d70a0]   404596 ms: Mark-sweep 10095.3 (10286.0) -> 10079.8 (10286.5) MB, 6787.7 / 0.0 ms  (average mu = 0.043, current mu = 0.002) allocation failure scavenge might not succeed
  | <--- JS stacktrace --->
  | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
  `

**Comment by edmundloo** [comment] 2021-11-09 00:06
> I am getting the same error but with the provider `"hashicorp/aws@~> 3.64.2"`. Setting `export NODE_OPTIONS="--max_old_space_size=20384"` did not work on my side.
> 
> The output is: `| <--- Last few GCs ---> | [933216:0x54d70a0] 397793 ms: Mark-sweep 10091.3 (10282.0) -> 10079.4 (10286.0) MB, 6808.6 / 0.0 ms (average mu = 0.081, current mu = 0.002) allocation failure scavenge might not succeed | [933216:0x54d70a0] 404596 ms: Mark-sweep 10095.3 (10286.0) -> 10079.8 (10286.5) MB, 6787.7 / 0.0 ms (average mu = 0.043, current mu = 0.002) allocation failure scavenge might not succeed | <--- JS stacktrace ---> | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

I had a similar failure. The mistake I made was not actually making sure I actually had the memory available for node to use on my device. It ended up working when I closed everything I could that was taking up memory and ran the command again.

**Comment by jcdan3** [comment] 2021-11-09 00:50
Thanks for the quick reply. I did make sure that I had sufficient RAM available and still facing the same issue.
Any other idea? 
Did you had to reload node or npm so that the setting is applied?

**Comment by edmundloo** [comment] 2021-11-09 00:52
> Thanks for the quick reply. I did make sure that I had sufficient RAM available and still facing the same issue. Any other idea? Did you had to reload node or npm so that the setting is applied?

I didn't need to, but I did monitor my RAM usage to make sure that the setting did apply to me. I didn't have to do anything extra to make it work.

**Comment by waxb** [comment] 2021-11-09 08:48
@edmundloo  do you get this message when it has started generating?
```
found NODE_OPTIONS environment variable without a setting for --max-old-space-size.
The provider generation needs a substantial amount of memory (~6-7GB) for some providers and languages.
So cdktf-cli sets it to NODE_OPTIONS="--max-old-space-size=10240" by default. As your environment already contains
a NODE_OPTIONS variable, we won't override it. Hence, the provider generation might fail with an out of memory error.
```
If not then you are still having the 10GB limit and from your crash output seems like this is the case.

**Comment by jcdan3** [comment] 2021-11-09 13:35
@waxb In your original post, it looks like your talked about setting the variable:
`NODE_OPTIONS=--max-old-space-size=13384`
but also
`NODE_OPTIONS=--max_old_space_size=13384`

not sure what the impact is, but from the documentation the right way is `--max-old-space-size`

Also, from looking at the [code](https://github.com/hashicorp/terraform-cdk/blob/36e350bf840bd55a908aea566842105abc6be553/packages/%40cdktf/provider-generator/lib/get/constructs-maker.ts#L319) the logic seems to prevent from using this.

I am no node expert, but my understanding is that if we set `NODE_OPTIONS=--max-old-space-size=13384`, then we fall in the else of line 319, which overide the NODE_OPTIONS.

**Comment by waxb** [comment] 2021-11-09 14:43
@jcdan3 
See that the `--max-old-space-size` is copied from the `console.warn` output and it is a direct flag for node, I tried to export it as well and didn't know why it was not working then realised from the source code that it is not actually invoked so I tried it with underscores and at viola, it worked.
You can see the workaround using underscores, but I'll make a note on the original post to highlight this.

**Comment by jcdan3** [comment] 2021-11-09 16:28
Thanks for the feedback. I was not able to succeed with `--max_old_space_size` with CDKTF-CLI 0.7.
I found another way around which was to update to  CDKTF-CLI 0.8 (pre-release).

This solved my issue.

**Comment by waxb** [comment] 2021-11-09 18:05
@jcdan3 
I guess because of [this](https://github.com/hashicorp/terraform-cdk/blob/7c823088281f66ec6a70e7297324d8e825ffed29/packages/%40cdktf/provider-generator/lib/get/constructs-maker.ts#L319) from [here](https://github.com/hashicorp/terraform-cdk/pull/1265).

**Comment by jcdan3** [comment] 2021-11-09 18:08
@waxb Agreed, I monitored my RAM and it was roughly 12.5 GB.

**Comment by DanielMSchmidt** [comment] 2021-11-25 14:35
@waxb Is this solved with 0.8 for you as well?

**Comment by waxb** [comment] 2021-12-07 10:51
@DanielMSchmidt 
In theory, [yes](https://github.com/hashicorp/terraform-cdk/blob/158d8575f520f17a5adf76d46ad9840e5888cca8/packages/%40cdktf/provider-generator/lib/get/constructs-maker.ts#L319).

**Comment by DanielMSchmidt** [comment] 2021-12-07 11:52
👍 Great, then I'll close the issue for now

**Closed by DanielMSchmidt** 2021-12-07 11:52 UTC
Labels: bug, waiting-on-answer, language/golang, provider/azure

**Comment by adeturner** [comment] 2022-06-20 13:29
+1 to prioritise the fix for this, I didnt see any min specs in the docs I'm running and I have this

8GB WSL ubuntu instance + 2GB swap
go 1.8.3
node 18.4.0
Terraform v1.2.3
cdktf 0.11.2

By shutting down vscode I managed to "cdktf get" to complete but "cdftk synth" keeps bombing
