### ISSUE TITLE
cdktf-provider-aws: Java cannot find cdktf dependency during mvn compile

### ISSUE THREAD

**Issue by rjensen98** [hashicorp/terraform-cdk#3001] opened 2023-07-12 01:39 UTC
### Expected Behavior

Running `mvn clean compile` on a plain cdktf project should result in `[INFO] BUILD SUCCESS`.

### Actual Behavior

Running `mvn clean compile` results in:

> [ERROR] Failed to execute goal on project java-test: Could not resolve dependencies for project com.mycompany.app:java-test:jar:0.1: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:14.0.4 -> com.hashicorp:cdktf:jar:[0.16.0,0.17.0): No versions available for com.hashicorp:cdktf:jar:[0.16.0,0.17.0) within specified range -> [Help 1]

...when cdktf-provider-aws v14.0.4 and cdk v0.16.3 are in the `pom.xml` dependencies (full stacktrace below)

> [ERROR] Failed to execute goal on project java-test: Could not resolve dependencies for project com.mycompany.app:java-test:jar:0.1: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:16.0.2 -> com.hashicorp:cdktf:jar:[0.17.0,0.18.0): No versions available for com.hashicorp:cdktf:jar:[0.17.0,0.18.0) within specified range -> [Help 1]

...when cdktf-provider-aws v16.0.2 and cdk v0.17.1 are in the `pom.xml` dependencies

In both cases, this happens with OpenJDK versions 8, 11, and 17.

Full stacktrace for v14.0.4:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.115 s
[INFO] Finished at: 2023-07-11T13:45:08-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project java-test: Could not resolve dependencies for project com.mycompany.app:java-test:jar:0.1: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:14.0.4 -> com.hashicorp:cdktf:jar:[0.16.0,0.17.0): No versions available for com.hashicorp:cdktf:jar:[0.16.0,0.17.0) within specified range -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project java-test: Could not resolve dependencies for project com.mycompany.app:java-test:jar:0.1: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:14.0. -> com.hashicorp:cdktf:jar:[0.16.0,0.17.0)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:269)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.mycompany.app:java-test:jar:0.1: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:14.0.4 -> com.hashicorp:cdktf:jar:[0.16.0,0.17.0)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:178)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:14.0.4 -> com.hashicorp:cdktf:jar:[0.16.0,0.17.0)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:291)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies (DefaultRepositorySystem.java:284)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:169)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for com.hashicorp:cdktf:jar:[0.16.0,0.17.0) within specified range
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.filterVersions (DefaultDependencyCollector.java:654)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:397)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.doRecurse (DefaultDependencyCollector.java:509)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:461)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
    at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:254)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies (DefaultRepositorySystem.java:284)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:169)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

### Steps to Reproduce

1. Create an empty directory
2. Create a pom.xml with the following contents:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>java-test</artifactId>
  <name>java-test</name>
  <version>0.1</version>
  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.hashicorp</groupId>
      <artifactId>cdktf</artifactId>
      <version>0.16.3</version>
    </dependency>
    <dependency>
      <groupId>software.constructs</groupId>
      <artifactId>constructs</artifactId>
      <version>10.0.25</version>
    </dependency>
    <dependency>
      <groupId>com.hashicorp</groupId>
      <artifactId>cdktf-provider-aws</artifactId>
      <version>14.0.4</version>
    </dependency>
  </dependencies>
  <build>
    <sourceDirectory>src/main/java</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.0.0</version>
        <configuration>
          <mainClass>com.mycompany.app.Main</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```
4. Using OpenJDK 8, 11, or 17 and Maven 3.9.2, run `mvn clean compile`
5. Alternatively, change cdktf from 0.16.3 to 0.17.1 and cdktf-provider-aws from 14.0.4 to 16.0.2, save, and run `mvn clean compile`

During the `mvn clean compile`, you'll note that it downloads both the `cdktf` and `cdktf-provider-aws` libraries:
```
$ mvn clean compile
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.mycompany.app:java-test >---------------------
[INFO] Building java-test 0.1
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf/0.17.1/cdktf-0.17.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf/0.17.1/cdktf-0.17.1.pom (5.1 kB at 8.1 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf-provider-aws/16.0.2/cdktf-provider-aws-16.0.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf-provider-aws/16.0.2/cdktf-provider-aws-16.0.2.pom (5.4 kB at 45 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.058 s
[INFO] Finished at: 2023-07-11T14:08:14-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project java-test: Could not resolve dependencies for project com.mycompany.app:java-test:jar:0.1: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:16.0.2 -> com.hashicorp:cdktf:jar:[0.17.0,0.18.0): No versions available for com.hashicorp:cdktf:jar:[0.17.0,0.18.0) within specified range -> [Help 1]
```

### Versions

cdktf debug
language: java
cdktf-cli: 0.16.3
node: v18.16.0
cdktf: 0.17.1
constructs: 10.0.25
jsii: 1.84.0
terraform: 1.3.8
arch: x64
os: darwin 21.6.0
java: 
maven: Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)Maven home: /usr/local/Cellar/maven/3.6.3_1/libexecJava version: 1.8.0_144, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jreDefault locale: en_US, platform encoding: UTF-8OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

### Providers

┌───────────────┬──────────────────┬─────────┬────────────┬──────────────────────────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF   │ Constraint │ Package Name                     │ Package Version │
├───────────────┼──────────────────┼─────────┼────────────┼──────────────────────────────────┼─────────────────┤
│ aws           │ 5.6.2            │ ^0.17.0 │            │ com.hashicorp.cdktf-provider-aws │ 16.0.2          │
└───────────────┴──────────────────┴─────────┴────────────┴──────────────────────────────────┴─────────────────┘

### Workarounds

Adding the `<exclusion />` block to the cdktf-provider-aws `<dependency />` in pom.xml fixes things...or at least allows things to resolve and compile.

```
    <dependency>
      <groupId>com.hashicorp</groupId>
      <artifactId>cdktf-provider-aws</artifactId>
      <version>14.0.4</version>
      <exclusions>
          <exclusion>
              <groupId>com.hashicorp</groupId>
              <artifactId>cdktf</artifactId>
          </exclusion>
      </exclusions>
    </dependency>
```

```
mvn clean compile
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.mycompany.app:java-test >---------------------
[INFO] Building java-test 0.1
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf-provider-aws/16.0.2/cdktf-provider-aws-16.0.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf/0.17.1/cdktf-0.17.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf/0.17.1/cdktf-0.17.1.jar (1.5 MB at 1.5 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf-provider-aws/16.0.2/cdktf-provider-aws-16.0.2.jar (116 MB at 21 MB/s)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ java-test ---
[INFO] Deleting /Users/rjensen/dev/sandbox/cdktf/java-test/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ java-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/rjensen/dev/sandbox/cdktf/java-test/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ java-test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/rjensen/dev/sandbox/cdktf/java-test/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.213 s
[INFO] Finished at: 2023-07-11T14:31:51-05:00
[INFO] ------------------------------------------------------------------------
```

### Anything Else?

Our last known successful execution of this was July 6th, 2023 at 9:01am CDT when our build pipeline ran.  Our first known failure was July 7th, 2023 at 6:56pm CDT.  After that, we re-triggered the pipeline job for the same code commit that was previously successful, and it failed with the issue described.

The "Actual Behavior" listed in this issue has been experienced on three different physical machines (all Macs), two different linux-based Docker containers, and across three different networks and internet providers.

We first recognized this issue while leveraging JSii to convert our cdktf constructs into Java.  Trying to narrow this issue down, we established a standalone Java cdktf project with `cdktf init --template java`, which also didn't quite work; it ended with
```
[INFO] Finished at: 2023-07-11T10:58:29-05:00
[INFO] ------------------------------------------------------------------------
========================================================================================================

  Your cdktf Java project is ready!

  cat help                Prints this message

  Compile:
    mvn compile           Compiles your Java packages

  Synthesize:
    cdktf synth [stack]   Synthesize Terraform resources to cdktf.out/

  Diff:
    cdktf diff [stack]    Perform a diff (terraform plan) for the given stack

  Deploy:
    cdktf deploy [stack]  Deploy the given stack

  Destroy:
    cdktf destroy [stack] Destroy the given stack

  Learn more about using modules and providers https://cdk.tf/modules-and-providers

Use Providers:

  You can add prebuilt providers (if available) or locally generated ones using the add command:
  
  cdktf provider add "aws@~>3.0" null kreuzwerker/docker

  All prebuilt providers are available on Maven Central: https://mvnrepository.com/artifact/com.hashicorp
  You can also add these providers directly to your pom.xml file.

  You can also build any module or provider locally. Learn more: https://cdk.tf/modules-and-providers

========================================================================================================
Checking whether pre-built provider exists for the following constraints:
  provider: aws
  version : latest
  language: java
  cdktf   : 0.16.3

Found pre-built provider.
Adding com.hashicorp.cdktf-provider-aws @ 14.0.4 to pom.xml
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/Users/rjensen/.nvm/versions/node/v18.16.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:41321)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
Collecting Debug Information...
/Users/rjensen/.nvm/versions/node/v18.16.0/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/Users/rjensen/.nvm/versions/node/v18.16.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:41321)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  stderr: ''
}

Node.js v18.16.0
```

Boiling it down to just a single empty directory with the pom.xml as described in "Steps to Reproduce" was the simplest way to reproduce this issue.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiehan** [comment] 2023-07-12 07:49
Duplicate of #2996 (the root issue is the same).

**Closed by xiehan** 2023-07-12 07:49 UTC
Labels: bug, duplicate

**Comment by rjensen98** [comment] 2023-07-12 14:37
Sorry, @xiehan for not seeing the duplicate.  Thanks a bunch for your attention to this!
