### ISSUE TITLE
Documentation: Complex Iterator example fails on plan

### ISSUE THREAD

**Issue by Maed223** [hashicorp/terraform-cdk#3157] opened 2023-09-29 14:31 UTC
### Description

Currently our example is as so:

```typescript
const complexIterator = TerraformIterator.fromList([
      {
        name: "website-static-files",
        tags: { app: "website" },
      },
      {
        name: "images",
        tags: { app: "image-converter" },
      },
    ] as any);

    new S3Bucket(this, "complex-iterator-bucket", {
      forEach: complexIterator,
      bucket: complexIterator.getString("name"),
      tags: complexIterator.getStringMap("tags"),
    });
```

Which synths fine (and it why we haven't caught it) but fails on plan with the following error:
```
│ Error: Invalid for_each set argument
│
│   on cdk.tf.json line 28, in resource.aws_s3_bucket.complex-iterator-bucket (complex-iterator-bucket):
│   28:         "for_each": "${toset([{\"name\" = \"website-static-files\", \"tags\" = {\"app\" = \"website\"}}, {\"name\" = \"images\", \"tags\" = {\"app\" = \"image-converter\"}}])}",
│
│ The given "for_each" argument value is unsuitable: "for_each" supports maps
│ and sets of strings, but you have provided a set containing type object.
```

Debugged it and got the following which works:

```typescript
const complexIterator = TerraformIterator.fromMap({
      "website-static-files": { name: "website-static-files", tags: { app: "website" } },
      "images": { name: "images", tags: { app: "image-converter" } }
});

new S3Bucket(this, "complex-iterator-bucket", {
  forEach: complexIterator,
  bucket: complexIterator.getString("name"),
  tags: complexIterator.getStringMap("tags"),
})
```

### Links

https://developer.hashicorp.com/terraform/cdktf/concepts/iterators#using-iterators-on-complex-types:~:text=Using%20Iterators%20on%20Complex%20Types

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiehan** [comment] 2023-10-12 15:28
Duplicate of #2452

**Closed by xiehan** 2023-10-12 15:28 UTC
Labels: documentation, duplicate, new
