### ISSUE TITLE
0.3.0 breaking local module in subdirectory

### ISSUE THREAD

**Issue by zmsy** [hashicorp/terraform-cdk#664] opened 2021-04-27 23:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf version: 0.3.0
typescript: 4.2.4

### Affected Resource(s)

`TerraformHclModule`

### Expected Behavior

```typescript
new TerraformHclModule(this, stackName, {
    source: "./terraform",
    variables: {
        ...
    },
});
 ```

Should result in module path being `./terraform`

### Actual Behavior

Module path is `../terraform`

Running subsequent `cdktf deploy` fails since it can't find the module.

### Steps to Reproduce

Create a subfolder with a terraform HCL module in it, then call `cdktf deploy`

### References

In `cdktf.out/stacks/<stack_name>/cdk.tf.json`, the rendered source is "../terraform"

Looks like it may have been introduced here: https://github.com/hashicorp/terraform-cdk/blob/e39f5e5847b9eb928f17be51d5f8f42ea5ab3112/packages/cdktf/lib/terraform-module.ts#L31

**Comment by jsteinich** [comment] 2021-04-28 01:36
@zmsy Where are you placing your module folder? The expected scenario is that any local module will be relative to your main folder. Since the terraform json is output to a subfolder (cdktf.out), it makes sense to go back a directory.

**Comment by zmsy** [comment] 2021-04-28 15:57
> @zmsy Where are you placing your module folder? The expected scenario is that any local module will be relative to your main folder. Since the terraform json is output to a subfolder (cdktf.out), it makes sense to go back a directory.

All of the commands are being run from the base directory.

**Comment by jsteinich** [comment] 2021-04-29 16:31
Thanks for the additional information. I'll double check where terraform is running from when using cdktf to make sure it aligns with that recent change for local module generation and the new multiple stacks changes.

**Comment by jsteinich** [comment] 2021-05-03 02:26
I confirmed that cdktf runs terraform from the directory of the stack itself. This means that path replacement actually needs to go up a 3 levels to get back to the project root.
It would be pretty simple to make that change, but I wonder how you envision it working @zmsy? Are you planning to copy the synthesized output back to the project root?

**Comment by skorfmann** [comment] 2021-05-03 07:56
> The goal was to keep a specific terraform module separate so that it would be easily installed by users who are using regular TF and not cdktf

This is something which could be achieved with plain Typescript as well - see this [blog post](https://dev.to/skorfmann/a-terraform-cdk-construct-which-doubles-as-native-terraform-module-447k).

However, back to this specific issue here. I think that local modules needs to be treated like an asset (see #648). In particular for remote workflows - such as Terraform Cloud - the Stack working directory needs to contain all files which are required to deploy the configuration (we essentially zip & upload the entire folder).

As a temporary workaround, would it be an option to use an absolute path?

**Comment by zmsy** [comment] 2021-05-03 17:37
> I confirmed that cdktf runs terraform from the directory of the stack itself. This means that path replacement actually needs to go up a 3 levels to get back to the project root.
> It would be pretty simple to make that change, but I wonder how you envision it working @zmsy? Are you planning to copy the synthesized output back to the project root?

Hadn't been planning on copying the output, no. The initial goal was to just run all the commands from the repository root i.e `cdktf synth && cdktf deploy`. Looking at @skorfmann's proposed solution in #648, that looks like treating a local module like an asset would work for this pattern.

**Comment by skorfmann** [comment] 2021-05-20 08:42
This can be tackled after https://github.com/hashicorp/terraform-cdk/pull/698 was merged.

**Comment by DanielTeraSky** [comment] 2021-08-19 08:14
I encounter the same issue with cdktf 0.5.0 and Python 3.7.5

**Comment by DanielMSchmidt** [comment] 2021-08-23 15:36
This can be solved now by either using 

a) the local module binding generation: https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-modules.md#generated-terraform-module-bindings

b) using the [Asset](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/terraform-assets.md) construct to move the HCL Module:

```ts
const tfModule = new Asset(this, "myModule", {
  path: "./terraform"
})

new TerraformHclModule(this, stackName, {
    source: tfModule.path,
    variables: {
        ...
    },
});
```

Let me know if this helps :)

**Comment by jsteinich** [comment] 2021-08-28 04:16
I believe local module binding generation will run into the same issue.

The module bindings don't currently expose providers or depends on configuration. They are both available for altering after construction via `add_provider()` and `dependsOn`.

**Comment by javiortizmol** [comment] 2021-09-09 00:30
> ```ts
> TerraformHclModule
> ```
The Asset solution doesn't work because you can't use relative path like "./terraform" should be an absolute path.

**Comment by DanielMSchmidt** [comment] 2021-12-01 11:01
If it is not solve please ping me here and I'll reopen the issue 👍

**Closed by DanielMSchmidt** 2021-12-01 11:01 UTC
Labels: bug, cdktf
