### ISSUE TITLE
Reusing Fn object doesn't render ${}

### ISSUE THREAD

**Issue by mmiermans** [hashicorp/terraform-cdk#1765] opened 2022-05-02 19:43 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
Working: 0.8.3
Broken: 0.9.0, 0.9.4

### Affected Resource(s)
Fn

### Debug Output
https://gist.github.com/mmiermans/9672e127bf91bd0120d3139c80925648

### Expected Behavior
Variables calling `Fn` should be reusable.

### Actual Behavior
The output in the HCL json is not wrapped in `${...}` when `Fn` objects are reused, which prevents the Terraform functions from being evaluated during `terraform apply` or `terraform plan`.

### Steps to Reproduce
I haven't created a minimal example yet, but the [above gist](https://gist.github.com/mmiermans/9672e127bf91bd0120d3139c80925648) contains some code that I hope makes this reproducible.

### References
Community Slack thread: https://pocket.slack.com/archives/C029B0RPB2P/p1651507070815049

**Comment by jsteinich** [comment] 2022-05-02 22:06
Thanks for reporting this. Fixing this issue is actively in-progress.
I'm going to close as a duplicate of https://github.com/hashicorp/terraform-cdk/issues/1447.

**Closed by jsteinich** 2022-05-02 22:06 UTC
Labels: bug, new
