### ISSUE TITLE
`cdktf init` defaults always to Yes on 'Would you like to use Terraform Cloud?'

### ISSUE THREAD

**Issue by conj40** [hashicorp/terraform-cdk#2963] opened 2023-06-24 00:22 UTC
### Expected Behavior

when running `cdktf init --template="python" --providers="aws@~>4.0"` you should be able to submit 'n' for the prompt "Would you like to use Terraform Cloud? (Y/n)"

### Actual Behavior

When you reach the prompt "Would you like to use Terraform Cloud? (Y/n)" no matter what you type it will always default to 'yes'. 

### Steps to Reproduce

`cdktf init --template="python" --providers="aws@~>4.0"`
Project Name aws
Project Description test
Would you like to use Terraform Cloud? (Y/n) n <------- This will default to 'Yes' even when specifying 'n'

### Versions

cdktf debug
language: null
cdktf-cli: 0.17.0
node: v20.3.1
terraform: 1.5.1
arch: arm64
os: darwin 22.1.0

M1 MacOS

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiehan** [comment] 2023-06-24 08:12
Duplicate of #2952.

**Closed by xiehan** 2023-06-24 08:12 UTC
Labels: bug, duplicate
