### ISSUE TITLE
Cdktf get: Cannot read property 'dots' of undefined

### ISSUE THREAD

**Issue by dzirg44** [hashicorp/terraform-cdk#1113] opened 2021-10-03 19:46 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```json
    "cdktf": "^0.6.3",
    "constructs": "^10.0.5"
    "cdktf-cli": "^0.6.3",
```

```bash
Node.js v14.17.6
```

### Affected Resource(s)
`cdktf get` - step

### Debug Output
https://gist.github.com/dzirg44/0d3d67950620e701e11b25c17be90064

### Expected Behavior
Get required providers/modules

### Actual Behavior
Error

### Steps to Reproduce
```sh
npx cdktf-cli init --local --template=typescript
npm install @cdktf/provider-aws
npm install -D cdktf-cli
npm run get
```

### Important Factoids
I use `Fedora 34`

**Comment by jsteinich** [comment] 2021-10-03 20:37
This seems likely to be caused by https://github.com/vadimdemedes/ink-spinner/issues/12.

`npm i -g cli-spinners@2.6.0` might be a way to workaround.

**Comment by nadworny** [comment] 2021-10-04 07:57
hey @jsteinich , I tried `npm i -g cli-spinners@2.6.0` but without success.

**Comment by LeonidLapshinAquaCloud** [comment] 2021-10-04 09:37
Hey, @nadworny 
```
npm install --global cdktf-cli@0.6.2 cli-spinners@2.6.0
npm install @cdktf/provider-azurerm
....
```
cdktf-cli and cli-spinners should be in one command I guess

**Comment by ansgarm** [comment] 2021-10-04 09:48
Hi!
I just found another workaround for TypeScript users: Install the cdktf-cli locally (e.g. as a devDependency) and also add a dependency to `cli-spinners@2.6.0` – this way that version will be used.
Example:
```
npx cdktf-cli init --local --template=typescript
npm install @cdktf/provider-aws
npm install -D cli-spinners@2.6.0 # <-- depend directly on this version
npm install -D cdktf-cli
npm run synth
```
(Running `get` without any dependencies fails and you don't need to run get for prebuilt providers)

For users of other languages I just added a similar hard dependency to `cli-spinners@2.6.0` to our cdktf-cli: #1116.

#881 would probably have prevented this kind of issue – and should prevent this in the future.

**Comment by ansgarm** [comment] 2021-10-04 10:47
The pre-release version is available as `npm install -g cdktf@0.6.3-pre.361`.
But we're also going to be releasing a proper release for this (#1117).

**Comment by sergio-deras** [comment] 2021-10-04 16:08
Is this going to be applied only to version `0.6.4` ?
We are using `0.4.1` at the moment and we have just faced the same issue this morning.

**Comment by diegoitaliait** [comment] 2021-10-04 16:34
# workaround

in the folder global `node_modules/cdktf-cli/node_modules/ink-spinner/build/index.js`

e.g.
```bash
/home/YOURUSER/.nvm/versions/node/v12.16.3/lib/node_modules/cdktf-cli/node_modules/ink-spinner/build/index.js
```

change the line 12 from this

```javascript
const spinner = cli_spinners_1.default[type];
```

to this 

```javascript
const spinner = cli_spinners_1['dots'];
```

ps: i know that is dirty, but it works 😁

**Comment by dzirg44** [comment] 2021-10-04 18:07
@ansgarm it seems that it resolved the issue, although I faced with another issue 
```
RangeError: Maximum call stack size exceeded
```
in the `node_modules/cdktf/lib/util.js:62`
but I think it would be better to create another bug and mention this bug there.
Thank you all guys .

**Comment by ansgarm** [comment] 2021-10-04 19:33
Hi @dzirg44, did that occur when running `cdktf get` for the aws provider? If yes, that's something we addressed in #1101.
But yeah, please feel free to file a separate bug for that 👍

**Comment by ansgarm** [comment] 2021-10-04 19:36
Hi @sergio-deras!
Which target language are you using the CDKTF with? The [workaround I mentioned](https://github.com/hashicorp/terraform-cdk/issues/1113#issuecomment-933322078) should work with older versions of the `cdktf` as well, however it is geared towards as TypeScript / JavaScript project.

**Comment by dzirg44** [comment] 2021-10-04 19:39
@ansgarm no on  `cdktf synth` , but I have to investigate it deeper.

**Comment by ansgarm** [comment] 2021-10-04 19:43
Oh, sounds like something else – feel free to file an issue either way. Even if you encounter that there was some kind of loop in your code or so. So that we can see whether we could've prevented it somehow 🕵️

**Closed** 2021-10-11 13:17 UTC
Labels: bug, dependencies, cdktf-cli, confirmed
