### ISSUE TITLE
Terraform Meta Arguments - Provisioners 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#94] opened 2020-06-06 08:34 UTC
Just stumble upon missing meta data for Terraform Resources: [Provisioners](https://www.terraform.io/docs/provisioners/index.html). They should be supported, in particular useful in regards to `NullResources`.

**Comment by ansgarm** [comment] 2021-08-16 10:57
@skorfmann Is this an (older) duplicate of https://github.com/hashicorp/terraform-cdk/issues/411?

**Comment by danieldreier** [comment] 2021-09-28 23:46
I'm closing this in favor of #411

**Closed by danieldreier** 2021-09-28 23:46 UTC
Labels: duplicate, enhancement, priority/important-longterm
