### ISSUE TITLE
"Incorrect attribute value type"

### ISSUE THREAD

**Issue by pmartindev** [hashicorp/terraform-cdk#223] opened 2020-07-20 23:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf: 0.0.12
typescript: Version 3.9.7

### Affected Resource(s)

cdk deploy

### Debug Output

https://gist.github.com/pmartindev/a5a741043975855a2a1a6fcacf4f549a

### Expected Behavior

I would expect the file to create default/null values for the cdk.json and the cdk deploy  to succeed

### Actual Behavior

Executing `cdk deploy` produces the above error.

### Steps to Reproduce

1. Create an AWS security group construct (see: https://gist.github.com/pmartindev/b1ab0aa678678b11aadc30a3b23859d0)
2. run the `cdk deploy` command
3. Check output to see that the error is shown, and the cdk.tf.json does not contain the values that the error message specifies (see: https://gist.github.com/pmartindev/c9e93ffa5c7fa8c939b07252c9e90bcf)

### Important Factoids

This appears to be an issue with the Terraform .json files. A workaround is to set the values to null, however, this is not possible with Typescript. 

UPDATE: Adding the missing attributes with null values in the cdk.tf.json allows the terraform file to run correctly. 

https://gist.github.com/pmartindev/314d083116776634ee4b4a5f07f40c95

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/8786

* #8786

**Comment by skorfmann** [comment] 2020-07-21 18:26
Thanks for reporting this issue. It's certainly a bug, the question is where. I've read terraform-providers/terraform-provider-aws#8786 and it seems like this is another occasion of #26. However, I doubt there will an upstream fix for this. 

It's essentially about providing defaults like this:

```json
            "ipv6_cidr_blocks": null,
            "prefix_list_ids": null,
            "security_groups": null,
            "self": null,
```

One option of dealign with this could be some kind of generator middleware which applies patches to specific elements of the schema (resources, data sources, provider). This could set the expected defaults.

**Comment by pmartindev** [comment] 2020-07-21 19:58
Thank you for the reply @skorfmann . Yes one option would be for providing defaults for particular cases such as that. On a much broader level it may help, for issues such as this, to be able to pass null values in TypeScript and translate those correctly to JSON as that is not possible at the moment.

**Comment by skorfmann** [comment] 2020-07-21 20:14
> On a much broader level it may help, for issues such as this, to be able to pass null values in TypeScript and translate those correctly to JSON as that is not possible at the moment.

Right, now I see what the issue is about. That's not possible at the moment, due to the way resources are synthesized. Each resource returns all attributes all the time, regardless of what's been set. `null` is then explicitly dropped when merging all constructs together. Even [escape hatches](https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/escape-hatch.md) won't work here. Gonna think about it.

**Comment by pmartindev** [comment] 2020-07-21 20:31
Exactly. After your other post, I was considering escape hatches, but if null values are dropped, then you're correct, that won't work.

I would say this is a pretty big issue, because at the moment, there is no way to create a security group with cdktf.

**Comment by skorfmann** [comment] 2020-07-21 20:42
> Exactly. After your other post, I was considering escape hatches, but if null values are dropped, then you're correct, that won't work.
> 
> I would say this is a pretty big issue, because at the moment, there is no way to create a security group with cdktf.

I stand corrected - `undefined` is filtered, `null` is not. I can synth this 

```ts
    const sg = new SecurityGroup(this, 'albsg', {
      name: "tf-ecs-alb-sg",
      description: "Allows traffic to the ALB.",
      ingress: [{
        protocol: "tcp",
        fromPort: 80,
        toPort: 80,
        cidrBlocks: ["0.0.0.0/0"]
      }],
      egress: [{
        protocol: "-1",
        fromPort: 0,
        toPort: 0,
        cidrBlocks: ["0.0.0.0/0"]
      }],
    });

    sg.addOverride("ingress.0.description", null)
```

to this 

```json
      "ingress": [
          {
            "protocol": "tcp",
            "from_port": 80,
            "to_port": 80,
            "cidr_blocks": [
              "0.0.0.0/0"
            ],
            "description": null
          }
        ],
```

**Comment by pmartindev** [comment] 2020-07-21 20:56
Interesting. I will try it out and see if that works, thanks!

**Comment by skorfmann** [comment] 2020-07-21 21:13
> . I will try it out and see if that works, thanks!

Not ideal, but should be an okish workaround for now.

**Comment by pmartindev** [comment] 2020-07-22 14:49
Well it worked for the time being, but I would definitely say it's not a maintainable work around... This is what a typical SG for an ECS task would look like.

https://gist.github.com/pmartindev/ad4e952ab039ba6e3c65bd62ce6cfdc7

**Comment by skorfmann** [comment] 2020-07-22 15:04
> Well it worked for the time being, but I would definitely say it's not a maintainable work around... This is what a typical SG for an ECS task would look like.

Absolutely agree. 

I read up on HCL2 and [null](https://www.terraform.io/docs/configuration/expressions.html#types-and-values) is technically something we should support. However, not sure what the impact is and if it's applicable to all attributes. There's a bit more research required. Plus, this wouldn't get us the right defaults either.

As mentioned earlier, we could think about providing a mechanism to provide defaults as part of the code generation process. Haven't really looked into this, but one basic idea would look like this:

```ts
public synthesizeAttributes(): { [name: string]: any } {
    return {
      // provide `null` default
      foo_bar: this._fooBar || null      
    };
```

This could be enabled by special cases for matches based on provider, resource name and attribute.

**Closed** 2021-02-05 15:09 UTC
Labels: bug
