### ISSUE TITLE
First class error support for cdktf

### ISSUE THREAD

**Issue by anubhavmishra** [hashicorp/terraform-cdk#131] opened 2020-07-02 19:38 UTC

**Comment by DanielMSchmidt** [comment] 2021-12-07 16:06
Closing this as aws/jsii#1840 is closed now 👍

**Comment by ansgarm** [comment] 2021-12-08 08:28
@DanielMSchmidt Hm.. the issue you linked was closed as a duplicate of https://github.com/aws/jsii/issues/47 😅

**Comment by schersh** [comment] 2022-03-16 15:45
Related to https://github.com/hashicorp/terraform-cdk/issues/1103

**Comment by xiehan** [comment] 2023-01-10 15:11
Some aspects of this issue have been resolved over the years. There might still be areas we can improve but if so, let's file new, separate and more specific issues; this issue itself is too broad and vague.

**Closed by xiehan** 2023-01-10 15:11 UTC
Labels: enhancement, cdktf, waiting-for-3rd-party-fix
