### ISSUE TITLE
Terraform Modules Output Parsing 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#286] opened 2020-08-06 13:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- All

### Affected Resource(s)

- Generated Modules

### Debug Output

![Screenshot 2020-08-06 at 15 16 37](https://user-images.githubusercontent.com/136789/89536282-f2493780-d7f7-11ea-8ae8-4ea60f773cc7.png)

### Expected Behavior

Module resources in the output should be updated properly

### Actual Behavior

Resources which are part of the output are not updated

### Steps to Reproduce

Generate module bindings and deploy

**Comment by danieldreier** [comment] 2021-09-28 19:22
@skorfmann I'm not super clear - is this still a valid issue?

**Comment by jsteinich** [comment] 2021-09-29 03:45
I think #403 is a duplicate of this and it has potentially been fixed for awhile.

**Comment by DanielMSchmidt** [comment] 2021-12-07 19:57
Closing this one as duplicate for #403

**Closed by DanielMSchmidt** 2021-12-07 19:57 UTC
Labels: bug, modules
