### ISSUE TITLE
`AwsDataLb` is missing `arn` parameter

### ISSUE THREAD

**Issue by rirze** [hashicorp/terraform-cdk#1669] opened 2022-03-29 15:30 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Latest `cdktf_cdktf_aws_provider` Python package.

### Affected Resource(s)

Data Source `AwsDataLb`

### Debug Output

Function signature in Python does not show `arn` input parameter. It should according to the Terraform AWS spec.

```python
|  __init__(self, scope: constructs.Construct, id: str, *, name: Optional[str] = None, tags: Union[cdktf.IResolvable, Mapping[str, str], NoneType] = None, count: Union[int, float, cdktf.IResolvable, NoneType] = None, depends_on: Optional[Sequence[cdktf.ITerraformDependable]] = None, lifecycle: Optional[cdktf.TerraformResourceLifecycle] = None, provider: Optional[cdktf.TerraformProvider] = None) -> None
 |      Create a new {@link https://www.terraform.io/docs/providers/aws/d/lb.html aws_lb} Data Source.
 |      
 |      :param scope: The scope in which to define this construct.
 |      :param id: The scoped construct ID. Must be unique amongst siblings in the same scope
 |      :param name: Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/aws/d/lb.html#name DataAwsLb#name}.
 |      :param tags: Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/aws/d/lb.html#tags DataAwsLb#tags}.
 |      :param count: 
 |      :param depends_on: 
 |      :param lifecycle: 
 |      :param provider:
```

### Important Factoids

Terraform Docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lb

**Comment by jsteinich** [comment] 2022-03-29 22:26
Related to #1602

**Comment by rirze** [comment] 2022-03-29 22:57
Same problem exists with `AwsDataLbListener`. It has no `arn` input parameter, but Terraform docs says it should. 

Could be some code generation bug related to `arn`?

**Comment by skorfmann** [comment] 2022-03-30 14:21
What @jsteinich said over here https://github.com/hashicorp/terraform-cdk/issues/1602#issuecomment-1055016512 - Gonna close this as duplicate of https://github.com/hashicorp/terraform-cdk/issues/1602 and add some context over there.

**Closed by skorfmann** 2022-03-30 14:21 UTC
Labels: bug, duplicate
