### ISSUE TITLE
EKS can't get OIDC issuer

### ISSUE THREAD

**Issue by shazi7804** [hashicorp/terraform-cdk#663] opened 2021-04-25 14:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
{
  "language": "typescript",
  "app": "npm run --silent compile && node main.js",
  "terraformProviders": [
    "aws@~> 2.0",
    "azurerm@~> 2.0.0"
  ]
}
```

- cdktf version
```
cdktf --version
0.3.0
```

### Affected Resource(s)

EksCluster

### Expected Behavior

Get EKS oidc url

### Actual Behavior

Want to get oidc issuer from EKS

```
new IamOpenidConnectProvider(this, 'EksOidc', {
    clientIdList: ["sts.amazonaws.com"],
    thumbprintList: [],
    url: eks.identity('0').oidc('0').issuer
})
```

But `EksClusterIdentity` class not include `issuer` function.

```
    /cdktf-samples/lib/aws/kubernetes.js:141
                url: eks.identity('0').oidc('0').issuer
                                       ^

    TypeError: eks.identity(...).oidc is not a function
        at new AwsEksGroups (/cdktf-samples/lib/aws/kubernetes.js:141:36)
        at new AwsEks (/cdktf-samples/main.js:81:9)
        at Object.<anonymous> (/cdktf-samples/main.js:121:1)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        at internal/main/run_main_module.js:17:47
```

In fact, `EksClusterIdentityOidc` included `issuer` but not any resource use it.

### Steps to Reproduce

cdktf deploy

### Workaround

new `EksClusterIdentityOidc` class with EKS resource

```
new IamOpenidConnectProvider(this, 'EksOidc', {
    clientIdList: ["sts.amazonaws.com"],
    thumbprintList: [],
    url: new EksClusterIdentityOidc(eks, 'identity[0]', 'oidc[0]').issuer
})
```

### References

none

**Comment by jsteinich** [comment] 2021-04-26 13:35
Pretty similar to #25.
Currently it's possible to get at the oidc cluster identity, but the return is just a terraform reference string as support for complex types at that level aren't yet fully supported.

That is a clever workaround which may be helpful when working on fixing this. Thanks.

**Comment by skorfmann** [comment] 2021-05-03 08:01
@jsteinich would you say it's a duplicate of #25?

**Comment by jsteinich** [comment] 2021-05-03 13:15
> @jsteinich would you say it's a duplicate of #25?

It's not identical, but I've been considering #25 to represent any situation where the code is generated with a fallback to `any`.
There are there cases in the generation whether that happens:

1. Complex computed optional types as described in #25 
2. Unknown complex types (in this case list<object<list<object>>>)
3. Maps of complex types

**Comment by DanielMSchmidt** [comment] 2022-04-07 12:17
@ansgarm Is this issue solved by your list work?

**Closed** 2022-05-11 12:35 UTC
Labels: bug, providers, v0.0, priority/important-soon, ux/configuration, size/large
