### ISSUE TITLE
Crash during destroying stack

### ISSUE THREAD

**Issue by sergeyzenchenko** [hashicorp/terraform-cdk#610] opened 2021-03-26 20:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.2.0

### Affected Resource(s)

cdktf destroy

### Debug Output

```
Something went wrong.
[2021-03-26T20:33:22.931] [ERROR] default - TypeError: Cannot read property 'startsWith' of undefined
    at exports.ResourceName (/usr/local/lib/node_modules/cdktf-cli/bin/cmds/ui/components/resource-name.js:18:43)
    at Jd (/usr/local/lib/node_modules/cdktf-cli/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:64:98)
    at ig (/usr/local/lib/node_modules/cdktf-cli/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:160:456)
    at hg (/usr/local/lib/node_modules/cdktf-cli/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:139:22)
    at bg (/usr/local/lib/node_modules/cdktf-cli/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:138:366)
    at Of (/usr/local/lib/node_modules/cdktf-cli/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:132:214)
    at /usr/local/lib/node_modules/cdktf-cli/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:30:115
    at exports.unstable_runWithPriority (/usr/local/lib/node_modules/cdktf-cli/node_modules/scheduler/cjs/scheduler.production.min.js:18:437)
    at hc (/usr/local/lib/node_modules/cdktf-cli/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:29:325)
    at kc (/usr/local/lib/node_modules/cdktf-cli/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:30:61) { componentStack:
   '\n    in Unknown\n    in div\n    in Box\n    in Unknown\n    in div\n    in Box\n    in div\n    in Box\n    in Unknown\n    in div\n    in Box\n    in Unknown\n    in Unknown\n    in Unknown\n    in ErrorBoundary\n    in Unknown\n    in App' }
z
```

### Expected Behavior

It should not crash

### Actual Behavior

it's crashing. I've tried to debug it. If you take a look at https://github.com/hashicorp/terraform-cdk/blob/main/packages/cdktf-cli/bin/cmds/ui/components/resource-name.tsx#L12 you will see that ```let [resource, resourceName] = prettyName.split('.')``` will return array with only one element if you pass string without dots. In my case, for some reason, resource name is "Warning" 
```{"name":"Warning","stackName":"appspector-tf"}```

### Steps to Reproduce

Deploy stack with GCP/GKE, destroy stack with GCP/GKE

### Important Factoids

nope

### References

* #0000

**Comment by sergeyzenchenko** [comment] 2021-03-26 20:34
I've modified code to ignore names without dots and now I got one more additional resource in "Resources" list 
```
 ~ WARNING              Warning             Warning
```

**Comment by jsteinich** [comment] 2021-03-27 21:31
I believe this is a duplicate of #582 which has a fix in the works currently.

**Comment by sergeyzenchenko** [comment] 2021-03-28 10:28
Yep you are right! Closing this one

**Closed** 2021-03-28 10:38 UTC
Labels: bug
