### ISSUE TITLE
cdktf get fails for Python env

### ISSUE THREAD

**Issue by cognitiaclaeves** [hashicorp/terraform-cdk#879] opened 2021-08-01 22:52 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Note: This runs in docker container, so root pip should be functional ... 

```
# pip freeze | grep cdk
cdktf==0.4.1
cdktf-cdktf-provider-aws==1.0.129
(lambda-example) /cdktg/cdktf-ex/lambda-example/cdktf.out/stacks/lambda-example # yarn global list
yarn global v1.22.5
info "cdktf-cli@0.4.1" has binaries:
   - cdktf
(lambda-example) /cdktg/cdktf-ex/lambda-example/cdktf.out/stacks/lambda-example # python --version
Python 3.8.10
```

( Same behavior is observed as above, with 0.5.0, however, there's currently no  'cdktf-cdktf-provider-aws' package,
so that package can't be used to work around `cdktf get` failing for 0.5.0 )

```
(lambda-example) /cdktg/cdktf-ex/lambda-example # pip freeze | grep cdktf && yarn global list
cdktf==0.5.0
yarn global v1.22.5
info "cdktf-cli@0.5.0" has binaries:
   - cdktf
```

cdktf.json:

```json
{
  "language": "python",
  "app": "pipenv run python main.py",
  "terraformProviders": [
    "aws@~> 3.52.0",
    "hashicorp/local@2.1.0"
  ],
  "terraformModules": [ "terraform-aws-modules/lambda/aws" ],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```

Pipfile:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[requires]
python_version = "3.8.10"

[packages]
cdktf = "~=0.4.1"
pylint = "*"
black = "*"
pytest = "*"
bandit = "*"
cdktf-cdktf-provider-aws = "~=1.0.129"
pip = "*"

[pipenv]
allow_prereleases = true
```

### Affected Resource(s)

(from cdktf.json):

```
"terraformProviders": [
    "aws@~> 3.52.0",
  ],
```

When the `"aws@~> 3.52.0",` is removed, it appears to work.

### Expected Behavior

imports/aws generated without error.

### Actual Behavior

```
Error: jsii compilation failed with non-zero exit code: null
  | (node:3792) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./helpers/" in the "exports" field module resolution of the package at /usr/local/share/.config/yarn/global/node_modules/es-abstract/package.json.
  | Update this package.json to use a subpath pattern like "./helpers/*".
  | (Use `node --trace-deprecation ...` to show where the warning was created)
  +----------------------------------------------------------------------------------
  | Command: /usr/local/share/.config/yarn/global/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-DGAPiJ
  +----------------------------------------------------------------------------------
    at newError (/usr/local/share/.config/yarn/global/node_modules/jsii-srcmak/lib/util.js:38:20)
    at ChildProcess.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/jsii-srcmak/lib/util.js:55:29)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
⠏ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: null
  | (node:3792) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./helpers/" in the "exports" field module resolution of the package at /usr/local/share/.config/yarn/global/node_modules/es-abstract/package.json.
  | Update this package.json to use a subpath pattern like "./helpers/*".
  | (Use `node --trace-deprecation ...` to show where the warning was created)
  +----------------------------------------------------------------------------------
  | Command: /usr/local/share/.config/yarn/global/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-DGAPiJ
  +----------------------------------------------------------------------------------
```

### Steps to Reproduce

```
export CDKTFVER='0.4.1'   # Or '0.5.0', but if >~0.4.x, comment out cdktf-cdktf-provider-aws in Pipfile
yarn global add cdktf-cli@${CDKTFVER}
pip install cdktf==${CDKTFVER}
( copy contents of cdktf.json and Pipfile, above ):
pipenv install
cdktf get
```

### Important Factoids

Running in docker container: https://gitlab.com/cognitiaclaeves/dkr-cdktf/-/blob/tg/Dockerfile

One more thing ... I'm not sure about what this line does (in cdktf.json):
```
"terraformModules": [ "terraform-aws-modules/lambda/aws" ],
```

But it appears to cause `cdktf get` to create `imports/aws/lambda/terraform-aws-modules/__init__.py` which looks to me like it might be equivalent to `imports/aws/__init__.py (when generated with cdktf-cli 0.3.0), or .../site-packages/cdktf_cdktf_provider_aws/__init__.py (for cdktf-cli 0.4.1 via pip package cdktf_cdktf_provider_aws)

-- but it contains different signatures, such as `create_role` and `environment_variables` 

... maybe I'm just at my limit from trying to parse out the above, but I wasn't able to determine what this was and if it relates to the package `cdktf_cdktf_provider_aws` ... it doesn't match terraform's documentation.

Where is it documented, or is the best way to work with it like this?:

- add it to the terraformModules section based on the path in terraform's documentation
- `cdktf get` to pull whatever it is
-  read through the new __init__.py file to figure out what it can be used for

**Comment by DanielMSchmidt** [comment] 2021-08-02 12:21
I was unable to reproduce this problem locally. What strikes me as odd is that you want to both use a pre-built provider and a locally built one, you should only need the aws one in your pipfile or your cdktf.json, not both. So removing the cdktf line seems to be the right move here. Regarding providers there is this part in the docs: https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-modules.md

Let me know it the docs help to clarify this and how we can improve the docs :)

**Comment by cognitiaclaeves** [comment] 2021-08-02 15:18
It's interesting that you're unable to reproduce the issue. What were your steps? Did you use the docker container?

Here's a more complete representation:
```
docker run --rm -it cdktg sh                                                                                                                                                                          jnorment@Js-MacBook-Pro
/cdktg # ls
/cdktg # apk add --no-cache vim
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/3) Installing xxd (8.2.2320-r0)
(2/3) Installing lua5.3-libs (5.3.6-r0)
(3/3) Installing vim (8.2.2320-r0)
Executing busybox-1.32.1-r6.trigger
OK: 388 MiB in 86 packages
/cdktg # vim cdktf.json
/cdktg # vim Pipfile
/cdktg # pipenv install
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /cdktg/Pipfile
Using /usr/bin/python3.8 (3.8.10) to create virtualenv...
⠸ Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 872ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/cdktg-ADvwaNLW, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.2.2, setuptools==57.4.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/cdktg-ADvwaNLW
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (fe0724)!
Installing dependencies from Pipfile.lock (fe0724)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 37/37 — 00:00:54
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
/cdktg # cdktf get
Newer version of Terraform CDK is available [0.5.0] - Upgrade recommended
⠇ downloading and generating modules and providers...

```

Why I'm using both the pre-built provider and a locally built one is referred to in the section after 'one more thing'. Here's a snippet of academic source code that I was using to help me understand what was going on:

```python

import importlib
mymodule = None

try:
    mymodule = importlib.import_module("imports.terraform_aws_modules.lambda.aws")
except ModuleNotFoundError as err:
    print(f'{err}: `cdktf get` -generated aws module not found, attempting to import from pypi imports.')

if not mymodule:
    try: 
        mymodule = importlib.import_module("cdktf_cdktf_provider_aws")
        mymodule.TerraformAwsModulesLambdaAws = mymodule.LambdaFunction
    except ModuleNotFoundError as err:
        sys.exit(f'{err}: module cdktf_cdktf_provider_aws not found. see notes in source (following this error.)')

...

def create_lambda(self, service_conf):
        service_name = service_conf["service_name"]
        handler = service_conf["handler"]
        create_lambda_options = {
            'function_name': service_name,
            'handler': handler,
            'runtime': "python3.8",
            'publish': True,
            'memory_size': 512,
            'timeout': 30,
            'tags': self.tags,
        }

        if hasattr(mymodule, 'LambdaFunction'):
            create_lambda_options.update({
                'role': lambdaRolePolicy,
                'environment': [ LambdaFunctionEnvironment(variables=LAMBDA_ENV_VARS) ]
            })            
        else:
            create_lambda_options.update({
                'create_role': True,
                'source_path': f"{project_dir}/src/handlers",
                'environment_variables': LAMBDA_ENV_VARS,
            })

        lambda_function = mymodule.TerraformAwsModulesLambdaAws(
            self,
            f"{service_name}-lambda_function",
            **create_lambda_options
        )

        return lambda_function.lambda_function_arn_output if \
            hasattr(lambda_function,'lambda_function_arn_output') else lambda_function.arn

```

Both the pre-built provider and the locally generated providers build the lambda. But only the locally built provider builds the supporting architecture (and has an option for create_role) -- so the locally generated provider can be used for rapid development, whereas the pre-built provider can't.

**Comment by ansgarm** [comment] 2021-08-24 15:44
Hi @cognitiaclaeves, I just tried to reproduce a [similar looking issue](https://github.com/hashicorp/terraform-cdk/issues/908#issuecomment-904753068) and failed to do so.

I wanted to share my suspicion here as well as this could be the same case here:
How much memory does your `cdktf get` process get?

The AWS Terraform provider can take a lot of memory (e.g. for Golang bindings it needed roughly 7GB of memory at a test I did some months ago).

**Comment by DanielMSchmidt** [comment] 2021-12-01 12:13
Hey there, this issue has been unanswered quite a while (the `waiting-on-answer` label tells me we wait for feedback here) so I will be closing this for now. If there is new information let me know and I will reopen the issue again 👍

**Closed by DanielMSchmidt** 2021-12-01 12:13 UTC
Labels: bug, documentation, waiting-on-answer, v0.4, priority/awaiting-more-evidence, provider/aws
