### ISSUE TITLE
Improper Formatting when using Escape Hatch and FQN. 

### ISSUE THREAD

**Issue by sabinayakc** [hashicorp/terraform-cdk#2472] opened 2023-01-10 17:46 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
```
language: typescript
cdktf-cli: 0.14.1
node: v16.17.0
cdktf: 0.14.1
constructs: 10.1.162
jsii: null
terraform: 1.3.2
arch: x64
os: linux 5.10.102.1-microsoft-standard-WSL2
```
### Affected Resource(s)
- CDKTF Typescript

```
    const subnet = new TerraformVariable(this._scope, "subnet-map", {
      type: VariableType.MAP,
      description: "A Map of Subnets to create"
    });

    subnet.addValidation({
      condition: `\${length(${subnet.fqn}) <= 16}`,
      errorMessage: "VPC Subnets should not be more than 16."
    });
```

### Expected Behavior

When using escape hatches to refer to the `FQN` of the resource, I should be able to get the resource without the braces  `{}` and `$` sign.  

In `cdktf.json` ,
```
      "description": "A Map of Subnets and their tags to create",
      "type": "map",
      "validation": [
        {
          "condition": "${length(var.subnet-map) <= 16}",
          "error_message": "VPC Subnets should not be more than 16."
        }
      ]
    }
```

### Actual Behavior

When using escape hatches to refer to the `FQDN` of the resource, I get improper formatting with the braces  `{}` and `$` 

In `cdktf.json` ,
```
      "description": "A Map of Subnets and their tags to create",
      "type": "map",
      "validation": [
        {
          "condition": "${length(${var.subnet-map}) <= 16}",  --> INVALID | Extra $ and braces {} 
          "error_message": "VPC Subnets should not be more than 16."
        }
      ]
    }
```

### Steps to Reproduce

- Use escape hatch and refer to the resources FQN, by doing `resourceName.fqn`.
- Run Synth. 

### Important Factoids

- However, the following works using `friendlyUniqueId` 
```
    subnet.addValidation({
      condition: `\${length(var.${subnet.friendlyUniqueId}) <= 16}`,
      errorMessage: "VPC Subnets should not be more than 16."
    });

--- cdktf.json
"condition": "${length(var.subnet-map) <= 16}",

```

**Comment by jsteinich** [comment] 2023-01-21 16:37
I think this is the same as #1641

**Comment by xiehan** [comment] 2023-06-01 14:09
I'm going to close this as a duplicate of #1641.

**Closed by xiehan** 2023-06-01 14:09 UTC
Labels: bug, duplicate, cdktf, size/medium, feature/tokens, bug/has-workaround
