### ISSUE TITLE
Nested tokens are not escaped when `Fn.format` is used on them

### ISSUE THREAD

**Issue by Gerrit-K** [hashicorp/terraform-cdk#1684] opened 2022-04-04 15:58 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* NodeJS 16
* cdktf 0.10.1

### Affected Resource(s)

Probably any, but I just tested with `StringResource` from `@cdktf/provider-random`

### Debug Output

<details><summary>debug output</summary>

```
yarn run v1.22.18
$ CDKTF_LOG_LEVEL=debug cdktf synth
[2022-04-04T17:41:21.284] [DEBUG] default - {
  "terraform_version": "1.1.7",
  "platform": "darwin_amd64",
  "provider_selections": {},
  "terraform_outdated": false
}

[2022-04-04T17:41:21.320] [DEBUG] default - v17.8.0

[2022-04-04T17:41:21.357] [DEBUG] default - Terraform v1.1.7
on darwin_amd64

Generated Terraform code for the stacks: stage
✨  Done in 8.33s.
```
</details>

### Expected Behavior

Outputs should escape all tokens:

```json
  "output": {
    "additional_output": {
      "value": "${random_string.id.result}"
    },
    "direct_output": {
      "value": "${random_string.id.result}"
    },
    "formatted_output": {
      "value": "${format(\"%s\", random_string.id.result)}"
    }
  },
```

### Actual Behavior

One token is not escaped (see line 3):

```json
  "output": {
    "additional_output": {
      "value": "random_string.id.result"
    },
    "direct_output": {
      "value": "${random_string.id.result}"
    },
    "formatted_output": {
      "value": "${format(\"%s\", random_string.id.result)}"
    }
  },
```

### Steps to Reproduce

Here's a snippet for typescript:

```typescript
// @ts-ignore
import { Fn, TerraformOutput, TerraformStack } from 'cdktf';
import { Construct } from 'constructs';
import { RandomProvider, StringResource } from '@cdktf/provider-random';

export class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new RandomProvider(this, 'random');

    const resource = new StringResource(this, 'id', { length: 1 });
    const nested = { value: resource.result };
    new TerraformOutput(this, 'direct_output', {
      value: resource.result,
    });
    new TerraformOutput(this, 'additional_output', {
      value: nested.value,
    });
    new TerraformOutput(this, 'formatted_output', {
      // if you replace the Fn.format call with a static string, everything works
      // value: 'static',
      value: Fn.format('%s', [nested.value]),
    });
  }
}
```

If it is run as above, the `additional_output` will not be escaped in the json output. Interestingly this happens only for the mapped/nested variable (i.e. the one that's wrapped in an object). It probably has something to do with the new token handling since `0.9.0`, because the exact same code works with `0.8.*`. I hope I didn't overlook something obvious when I attempted to upgrade our code to the newer version. Also, if the title doesn't fit, please feel free to adjust it.

**Comment by ansgarm** [comment] 2022-04-05 08:15
Hi @Gerrit-K 👋
Thank you for the great reproduction example. The underlying issue for this is #1447.

As `nested.value` is used in two outputs with different states of being an inner expression. If you remove the `formatted_output` the `direct_output` will be properly escaped. This will also happen if you create a `const nested2 = { value: resource.result }` and use that one in either one of the two outputs.

As you are using TypeScript, a quite hacky workaround could be to use an anonymous class and a getter which would return a new reference to `resource.result` whenever it is used:
```ts
const nested = new (class {
  get value() {
    return resource.result;
  }
})();
```

**Comment by ansgarm** [comment] 2022-04-05 08:16
I'm going to close this as it is a duplicate of #1447. But feel free to comment here or on the other issue with any further feedback 🙂

**Closed by ansgarm** 2022-04-05 08:16 UTC
Labels: bug, duplicate

**Comment by Gerrit-K** [comment] 2022-04-05 13:57
Hi @ansgarm and thanks for the quick reply! Although I don't understand the internals in detail, I can see how the issues are related, so I'm fine with closing it. I'm just a bit confused about the other issue being reported for `0.8`, whereas my particular case worked in that version.

Anyhow, your suggested hack (😄 ) is interesting and I might be able to adjust it to my needs, but I'm really looking forward for the fix 👍

**Comment by ansgarm** [comment] 2022-04-05 16:24
Yeah, you're right! I missed the versions 😅
Weird that it worked in 0.8 for you.. Maybe we introduced the issue in some patch version of 0.8 🤔
Nevertheless, I don't think it makes sense to figure out why exactly that worked in 0.8 if it is broken in more recent versions and we already know why 😄 (It has to do with how inner expressions are resolved, but yeah, those are details)
