### ISSUE TITLE
diff command should support stack wildcards

### ISSUE THREAD

**Issue by lion3ls** [hashicorp/terraform-cdk#2957] opened 2023-06-22 09:34 UTC
### Description

`cdktf diff` does not support stack wildcards like `production-*`.

cdktf should align with the usage of the other commands like `deploy` and `destroy`.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment] 2023-06-22 09:58
Hi @lion3ls 👋

Thank you for raising this. It seems to be related or a duplicate of https://github.com/hashicorp/terraform-cdk/issues/2235

Daniel also posted a [comment there](https://github.com/hashicorp/terraform-cdk/issues/2235#issuecomment-1303289768) outlining why we don't support the wildcard on `diff`.

**Comment by ansgarm** [comment] 2023-06-23 07:25
Closing this as a duplicate of #2235

**Closed by ansgarm** 2023-06-23 07:25 UTC
Labels: enhancement, new
