### ISSUE TITLE
Generated providers should require the version of the provider they were built against or higher

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#318] opened 2020-08-17 12:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently if you have `aws@~> 2.0` in your cdktf.json file it will go grab the latest 2.x version of the aws provider. `aws_provider.ts` will have `providerVersionConstraint: '~> 2.0'`. It would be helpful if instead it has `providerVersionConstraint: '~> 2.70.0'` (or whatever version it was built against). This is especially helpful for #98 so that you know which version it was built against, but would also be nice when committing local versions of the provider.

I think there may also be a potential issue since Terraform won't download a new version if you have one cached locally and aren't running Terraform init. If one team member adds a resource that was added in a newer version than what you have, I believe the error message that you'll get isn't the most informative.

### References

#98 
https://github.com/skorfmann/cdktf-provider-aws

**Comment by skorfmann** [comment] 2020-08-17 14:56
I think that's a duplicate of https://github.com/hashicorp/terraform-cdk/issues/43 ?

**Comment by skorfmann** [comment] 2020-08-17 15:10
Right, that makes sense 👍

**Closed** 2022-03-25 13:54 UTC
Labels: enhancement, priority/important-soon, provider get / generation, size/medium
