### ISSUE TITLE
Java fails to compile with 'error: too many parameters' when synthesizing Vpc

### ISSUE THREAD

**Issue by digitalsanctum** [hashicorp/terraform-cdk#470] opened 2020-12-23 18:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Language: Kotlin (using Java libraries)
implementation("com.hashicorp:cdktf:0.0.19")
implementation("software.constructs:constructs:5.0.0")

### Debug Output

Gist with full debug/stacktrace: https://gist.github.com/digitalsanctum/0fe5717377597d2df906baa44ef7cef4

### Expected Behavior

Should synthesize without issue.

### Actual Behavior

Java compile fails with `error: too many parameters` on the VpcOptions builder.

### Steps to Reproduce

See this repo: https://github.com/digitalsanctum/cdktf-kotlin-demo

### References

* #0000

**Comment by jsteinich** [comment] 2020-12-24 04:48
Unfortunately there isn't an easy fix for this. See #365.

**Comment by skorfmann** [comment] 2021-01-05 14:10
Closing as duplicate of #365

**Closed by skorfmann** 2021-01-05 14:10 UTC
Labels: bug, duplicate, java, modules
