### ISSUE TITLE
Module output is treated as a string when it isn't

### ISSUE THREAD

**Issue by jleechpe** [hashicorp/terraform-cdk#2115] opened 2022-09-13 18:50 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.12.1

### Affected Resource(s)

non-string Module Outputs

### Expected Behavior

We have a terraform module to generate Tags for Azure based on Subscription/context/variables.  This takes in various strings and then returns a map corresponding to the tags we want included.  When using this with Terraform it behaves as expected and everything works.

### Actual Behavior

With CDKTF the azurerm tag element expects a map/dictionary but it views the module output as being passed back as a string

### Steps to Reproduce

Create a Terraform Output from a Module that returns a map rather than a string and try to use the output directly for a resource input that expects a map (AzureRM Tags)

**Comment by ansgarm** [comment] 2022-09-14 08:40
Hi @jleechpe 👋

I'll close this as a duplicate of https://github.com/hashicorp/terraform-cdk/issues/287.

That said, the current workaround is to use e.g. `Token.asMap(yourModule.mapOutput)` or `Token.asStringMap(yourModule.mapOutput)`.

**Closed by ansgarm** 2022-09-14 08:40 UTC
Labels: bug, new
