### ISSUE TITLE
TFE well-known endpoints not being used

### ISSUE THREAD

**Issue by hoo29** [hashicorp/terraform-cdk#1893] opened 2022-06-23 19:11 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.11.2

### Affected Resource(s)

cdktf cli
npm package "@skorfmann/terraform-cloud"

### Description

The API path in the underlying terraform cloud library is hardcoded to `/api/v2` 
https://github.com/skorfmann/terraform-cloud/blob/ed3f22da9ccd7ae6fdc983633173deef3a07df2c/src/api/terraformCloudApiClient.ts#L6

This means TFE installations with custom paths specified at `.well-known/terraform.json` do not work as all calls return a 404.

### Expected Behavior

The `well-known` configuration is used instead of hardcoded values.

### References

- #1854

**Comment by hoo29** [comment] 2022-06-24 08:12
An example of the well known endpoint is the main terraform cloud one at https://app.terraform.io/.well-known/terraform.json

**Comment by DanielMSchmidt** [comment] 2022-07-15 11:35
Yeah that's not ideal, we are thinking about replacing our custom TFC API calls with Terraform so we can implement all the features once instead of twice, the issue is #1913

**Comment by hoo29** [comment] 2022-09-12 11:02
@DanielMSchmidt - #1913 has been marked as resolved but I am still seeing the same error. Is this expected?

**Comment by DanielMSchmidt** [comment] 2022-09-12 11:16
Yeah unfortunately it's expected. It's a bug we have been planning to fix by moving to Terraform directly for all TFC/TFE related interaction, but we haven't finalised the fix yet

**Comment by hoo29** [comment] 2022-09-12 11:18
Ah okay, so there is more to it then just the plan and apply which was fixed in #1913. Is there an open issue for moving all operations to the terraform cli I can follow?

**Closed** 2023-01-04 12:39 UTC
Labels: bug, terraform cloud, cdktf-cli, confirmed, priority/important-longterm, size/medium, tech-debt, terraform enterprise
