### ISSUE TITLE
Design improved provider get experience

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#1084] opened 2021-09-27 22:07 UTC
This is a meta-issue tracking a set of possible improvements around using providers. This is a research and design task. 

There are several issues to be solved:

1. Users do not reliably understand how to use pre-built providers [Now]
https://github.com/hashicorp/terraform-cdk/issues/831
https://github.com/hashicorp/terraform-cdk/issues/953
https://github.com/hashicorp/terraform-cdk/issues/318

2. Interacting with cdktf.json is a point of friction while getting started [Now]
https://github.com/hashicorp/terraform-cdk/issues/228
https://github.com/hashicorp/terraform-cdk/issues/160
https://github.com/hashicorp/terraform-cdk/issues/228

3. Synthesizing CDKTF provider bindings is relatively slow [Later] 
https://github.com/hashicorp/terraform-cdk/issues/791
https://github.com/hashicorp/terraform-cdk/issues/578

4. Finding provider documentation is hard on people [Later]
https://github.com/hashicorp/terraform-cdk/issues/748

**Goal**
The purpose of this task is to reserve design time for designing a simplified UX that address as many of these inter-connected issues as can be feasibly built within a one-month iteration. The outcome of this should be scoped, ticketed work in the next release (and subsequent ones, if it won't fit) that references back to this issue.

**Proposed Design Direction**
My sense is that this is a case where the CLI workflow should be improved such that people don't need to understand (or read documentation on) provider generation as a pre-requisite to using cdktf in typical, basic use cases. I'm open to alternative solutions.

I believe there are two parts to solving this:
1. Improve UX for interacting with the provider configuration and generation workflow, and
2. Fix performance issues, metadata information, odds and ends of small papercut issues that are technically not related but are thematically connected to this UX

My proposal (to solve items 1 and 2) is for a [CLI subcommand](https://github.com/hashicorp/terraform-cdk/issues/877) that is the primary interface to adding, removing, and updating providers. Ideally, this would also help people generate/find provider documentation, but that might be too much scope expansion.

See also:
* https://github.com/hashicorp/terraform-cdk/issues/218
* [local providers](https://www.terraform.io/docs/cli/config/config-file.html#development-overrides-for-provider-developers) are notoriously hard for people to figure out how to install. Ideally, we should provide a simple workflow that allows people to install, generate bindings for, and use a local provider without having to figure out what Terraform folder to put them in.

**Comment by chiayuan** [comment] 2021-09-29 02:13
So excited about this improvement!
Besides for the improvement of `cdktf get`,
I would like to share some thoughts, and experience when I using `imports` constructs.

My development environment is `VSCode` and `Pylance` as a language server for Python.
The main provider we used is `AWS Provider`. I know it is a huge provider to handle.
The problem is the **IntelliCode** and **Code navigation** feature of Pylance, which can speed up our development, barely work when importing  `AWS Provider`:
![image](https://user-images.githubusercontent.com/3193372/135191124-ab81f9a8-95ff-4098-bc4c-8b98de39007c.png)
However, they work well with others such as `Kubernetes Provider`.
![image](https://user-images.githubusercontent.com/3193372/135191213-5ff0ba8e-3fce-4527-a299-81ff458f9f1e.png)
Probably `AWS Provider` is just too large for a language server to handle?

The workaround is I always keep the imported `__init__.py` opened and **manually** search any resource I would like to use.
Wondering if anyone here has the same experience, or any feedback?

Thanks a lot to CDKTF team!

**Comment by jsteinich** [comment] 2021-09-29 03:59
> I think it will be great if `cdktf get` can categorize resources into different modules by prefix.

@chiayuan That is already in-progress with #1083

**Comment by chiayuan** [comment] 2021-09-29 04:05
@jsteinich Wow, nice! Doesn't expect to see that coming so soon. Looking forward to it!

**Comment by jsteinich** [comment] 2022-02-21 13:47
Some suggestions on possibly renaming the command in https://discuss.hashicorp.com/t/cli-get-command-is-this-idempotent-why-does-it-rebuild-from-unaltered-source/35034/5.

**Comment by ansgarm** [comment] 2022-05-31 14:52
Closing this tracking issue, as we're going to research and work on the mentioned issues individually and this research issue is kinda outdated by now.

Feel free to file any other ideas you might have as new [feature requests](https://cdk.tf/feature)!

**Closed by ansgarm** 2022-05-31 14:52 UTC
Labels: enhancement, needs-research, priority/important-longterm, provider get / generation, size/medium
