### ISSUE TITLE
cdktf init " 'which' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by LucaMali** [hashicorp/terraform-cdk#267] opened 2020-07-30 09:59 UTC
When launching the "cdktf init" command to prepare the project folder with python language i get this error "'which' is not recognized as an internal or external command, operable program or batch file. Unable to find "pipenv". Install from https://pipenv.kennethreitz.org" 

I'm on Windows 10 and even if pipenv is installed I get the "Unable to find 'pipenv' error" 

Terraform version : v0.12.29
Node version : v12.18.2
Yarn version : 1.22.4
Pipenv : version 2020.6.2
Python 3.7.8

![Capture](https://user-images.githubusercontent.com/46742509/88909873-f3102580-d25b-11ea-90e9-e9bd00cc2137.PNG)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by skorfmann** [comment] 2020-07-30 10:57
Hey @LucaMali - thanks for creating this issue. 

This looks like a system specific issue to me. @jsteinich since you have more experience running `cdktf` on windows, do you have an idea what could cause this?

**Comment by jsteinich** [comment] 2020-07-30 12:45
I can confirm the issue. It is caused by https://github.com/hashicorp/terraform-cdk/blob/d785af4bf2dad8f1a30b34b8e751ece967c7680d/packages/cdktf-cli/templates/python/.hooks.sscaff.js#L9

I'll try to work on a fix tonight.

**Comment by LucaMali** [comment] 2020-07-30 12:50
Ok thank you.
I'm gonna wait for updates.

**Comment by skorfmann** [comment] 2020-08-24 12:22
Fixed by #270

**Closed by skorfmann** 2020-08-24 12:22 UTC
Labels: bug, windows
