### ISSUE TITLE
token usage dependent on the order they are used (new with v0.9.0)

### ISSUE THREAD

**Issue by marengaz** [hashicorp/terraform-cdk#1520] opened 2022-01-27 19:07 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

python
v0.9.0 (bug not present in v0.8.6)

### Affected Resource(s)

all?

### Expected Behavior

token usage should be independent on the order they are used

### Actual Behavior

when tokens are nested then used out of order, they dont resolve properly

### Steps to Reproduce

```py
from constructs import Construct
from cdktf import App, TerraformStack, TerraformVariable, Fn

from imports.google import (
    BigqueryDataset,
    GoogleProvider,
)


class MyStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)
        google = GoogleProvider(self, "google")

        some_replacement = TerraformVariable(self, "some_replacement", type="string").string_value

        my_token = Fn.replace("bar REPLACE_ME", "REPLACE_ME", some_replacement)

        my_other_token = Fn.jsonencode(dict(foo=my_token))

        ds = BigqueryDataset(
            self,
            "test99_bq_dataset",
            provider=google,
            description=my_other_token,
            project="my-project",
            dataset_id="test99",
            location="EU",
        )

        ds2 = BigqueryDataset(
            self,
            "test9_bq_dataset",
            provider=google,
            description=my_token,
            project="my-project",
            dataset_id="test99",
            location="EU",
        )


def main():
    app = App()
    MyStack(app, "my_stack")
    app.synth()


if __name__ == "__main__":
    main()

```

above code synthesises:
```json
{
  ...
  "resource": {
    "google_bigquery_dataset": {
      "test99_bq_dataset": {
        "dataset_id": "test99",
        "description": "${jsonencode({foo = replace(\"bar REPLACE_ME\", \"REPLACE_ME\", var.some_replacement)})}",
        ...
      },
      "test9_bq_dataset": {
        "dataset_id": "test99",
        "description": "replace(\"bar REPLACE_ME\", \"REPLACE_ME\", var.some_replacement)",
        ...
      }
    }
  }
}
```

note that the description for "test9_bq_dataset" will not resolve because of the missing `${...}`

### Important Factoids

the reason for this (which took me ages to figure out!) is because `my_token` has previously been used in the definition for `my_other_token`

moving `ds2 = BigqueryDataset(...)` above `ds = BigqueryDataset(...)` in main.py synthesises the correct result

### References

- unexpected breaking change as a result of https://github.com/hashicorp/terraform-cdk/releases/tag/v0.9.0

**Comment by jsteinich** [comment] 2022-01-28 02:40
This sounds a lot like https://github.com/hashicorp/terraform-cdk/issues/1447, but that wasn't new in 0.9.

#910 may also be relevant.

**Comment by marengaz** [comment] 2022-01-28 09:28
hmm, potentially. i noticed this particular bug as a regression test failed when upgrading a production module from 0.8.6 to 0.9.0.
i must admit, i havent tried the recreation posted above in 0.8.6. only 0.9.0

**Comment by jsteinich** [comment] 2022-01-31 13:39
> hmm, potentially. i noticed this particular bug as a regression test failed when upgrading a production module from 0.8.6 to 0.9.0. i must admit, i havent tried the recreation posted above in 0.8.6. only 0.9.0

No worries. Either way it is a bug that should be fixed.

**Comment by DanielMSchmidt** [comment] 2022-02-04 15:35
A workaround for this issue is to store the entire class in a variable instead of the property. I will close this as duplicate of #1447, we should be tackling this soon :)

**Closed by DanielMSchmidt** 2022-02-04 15:35 UTC
Labels: bug, new
