### ISSUE TITLE
AppOptions: Define Outdir in the code raise a synth ERROR

### ISSUE THREAD

**Issue by caparisi** [hashicorp/terraform-cdk#3405] opened 2024-01-10 14:34 UTC
### Expected Behavior

With python, I want define the output dir directly in the code (without specify it in the command line) when I create the App object like : 
```python
#!/usr/bin/env python
from cdktf import App

cdktf_environment = App(outdir='out-environment-xxxxxxx.out')

# Custom CDKTF code ....

cdktf_environment.synth()
```
Synth cmd is : 
```bash
cdktf synth -a "pipenv run python ./environment-xxxxxxx.py" 
```

### Actual Behavior

When we execute the synth, we get the following error (error code 1): 
```bash
cdktf synth -a "pipenv run python ./environment-xxxxxxx.py" 

[2024-01-10T15:06:22.324] [ERROR] default - ERROR: synthesis failed, because app was expected to call 'synth()', but didn't. Thus "cdktf.out/manifest.json"  was not created: Error: Could not find manifest file at cdktf.out/manifest.json. In case --skip-synth was passed, please try again without the flag.   
```

The output itself is well generated, we could go in the stack generated file and execute terraform init/apply without any issue.

If we specify the ouput dir in the command line with `-o`, the issue don't happen

### Steps to Reproduce

1. Setup your cdktf with python project
2. Define the App object with the `output` param like `App(outdir='out-environment-xxxxxxx.out')`
3. Try to synth without the `-o` param

### Versions

**language**: Python 3.10.13 
**cdktf-cli**: 0.20.0
**node**: v20.9.0
**Terraform**: v1.6.6
**OS**: Linux x86_64
**Python dependency:** 
- cdktf = "~=0.20"
- constructs = "*"

### Providers

Python dependency: 
```
	cdktf-cdktf-provider-kubernetes = "~=11.0"
	cdktf-cdktf-provider-helm = "~=10.0"
	cdktf-cdktf-provider-postgresql = "~=11.0"
	cdktf-cdktf-provider-azurerm = "~=12.0"
	cdktf-cdktf-provider-azuread = "~=12.0"
	cdktf-cdktf-provider-random = "~=11.0"
	cdktf-cdktf-provider-time = "~=10.0"
```

### References

https://github.com/hashicorp/terraform-cdk/pull/3334

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment] 2024-01-11 10:18
Hi @caparisi 👋

This is currently required and by design. The CDKTF CLI invokes the `app` as a separate process and there is no further communication between the `app` and the CLI, so we can't pass the `outdir` that might've been passed to `App` back to the CLI for it to find the generated Terraform config.

So at this point, you have three options to pass the outdir to the CLI:
* via the `-o` / `--output` param
* via the `CDKTF_OUTDIR` environment variable
* via the `output` property in your `cdktf.json` config

Passing the `outdir` to the `App` is intended for testing purposes.

I'm curious: What is your underlying use-case? I guess you are dynamically generating it and aren't using a static string there?

**Comment by caparisi** [comment] 2024-01-11 11:29
Hi @ansgarm,

Thanks for your answer, I didn't found this clearly explained in the documentation but maybe I didn't looking to the right place ^^

Initially, we had 1 git repository  with 1 cdktf App. More we use it, more we had stacks and complexity so we split us infra in many different scripts (+ a kind of "common library" to do a lot of factorization/reusable code), each one call with the `-a` (e.g: `cdktf synth -a "pipenv run python ./environment-staging.py"`, ``cdktf synth -a "pipenv run python ./applications-staging.py"``). Each script has its own python "App" object. To have all different stack synth in same time, we had to add the `-o` param to synth in different folders. I used bash aliases to not have to enter the full command every time of course, but we have to specify it in documentation and take care to stay coherent between DevOps people to simplify some development.

From your explanation, I understand that the "right" way to do the things will be to create a folder to each App script in which we will have to init a cdktf App, isn't? If this is the case, I guess that we will stay the '-o' param because else we will have 8 different `cdktf.json` /`Pipfile` to update/maintain + the fact to have to move in each folder to run `cdktf` cli command, which is not a issue for CI but painful for daily development.

PS: To give you a bit of context. I work for a big non-profit humanitarian (8K employee, 20M beneficiary). We use CDKTF to manage in IaaS all our infrastructure.

**Comment by ansgarm** [comment] 2024-01-24 10:49
>  I understand that the "right" way to do the things will be to create a folder to each App script in which we will have to init a cdktf App, isn't?

Yes, that would be the recommended way based on the assumptions that the CDKTF CLI makes. However, I can see where you're coming from. So I wouldn't discourage your approach 👍

I added some more docs in #3463 for the `AppOptions#outdir` option that are hopefully easier to discover than this issue 😄

I'm going to link that PR to close this issue, once it's merged. If there's anything else you run into, don't hesitate to create a new issue!

**Closed** 2024-01-24 12:06 UTC
Labels: bug, new
