### ISSUE TITLE
high cpu usage when running cdktf deploy

### ISSUE THREAD

**Issue by trondhindenes** [hashicorp/terraform-cdk#571] opened 2021-02-18 10:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
```
╰─ cdktf --version
0.1.0-pre.186
```

### Expected Behavior
CPU usage when running `cdktf deploy` should be along the same lines as running `terraform apply`

### Actual Behavior
cpu usage is a lot higher than expected

### Steps to Reproduce
Whe running cdktf deploy against stacks with a lot of resources, the "resource update" process (e.g. _after_ cdktf has generated the terraform code) has high cpu usage. As far as I understand, under the hood it's essentially doing `terraform apply`, so I'm finding it weird that the `node` process alone pegs my cpu at 20%. Maybe its a too-aggressive wait-loop or something?

### Important Factoids
Using terraform `0.14.6`, not sure if that's relevant

**Comment by skorfmann** [comment] 2021-02-18 14:13
Thanks for creating this issue. 

> Whe running cdktf deploy against stacks with a lot of resources

Could you be more specific about the amount of resources we're talking about? Also, which OS are you working on?

> As far as I understand, under the hood it's essentially doing `terraform apply`

Yes, that's correct.

> so I'm finding it weird that the `node` process alone pegs my cpu at 20%. 

Could be related to either suboptimal handling of the Terraform interaction in the `cdktf cli` or potentially be related to the UI rendering (thinking about the spinners here in particular). That's something we'll have to dig into.

**Comment by trondhindenes** [comment] 2021-02-18 14:21
Thanks for the quick reploy.
I think we generate a couple of hundred terraform objects using the google provider. Lots of `google_project_service` objects. Running on `Ubuntu 20.04.2 LTS`

**Comment by skorfmann** [comment] 2021-02-18 14:28
> I think we generate a couple of hundred terraform objects using the google provider. 

Ok, I can imagine that this will take a toll on the cpu. This is slightly related to https://github.com/hashicorp/terraform-cdk/issues/115 - Resolving this would probably include limiting the number of resources rendered. So, something like only rendering currently updating resources. 

There isn't really a workaround in the `cdktf cli`. However, you could fallback to the `terraform cli` for applying for the time being.

**Comment by sergeyzenchenko** [comment] 2021-03-31 13:31
I've tried to debug this CPU usage issue and disabling animated spinners drops CPU usage from 20% to 3% on my machine :)

**Comment by sergeyzenchenko** [comment] 2021-04-01 19:07
@trondhindenes @skorfmann should be improved significantly by https://github.com/hashicorp/terraform-cdk/pull/618

**Comment by DanielMSchmidt** [comment] 2021-12-01 11:18
I could not reproduce this in the 0.7 version, if you still experience issues please let me know and I'll reopen the issue 👍

**Closed by DanielMSchmidt** 2021-12-01 11:18 UTC
Labels: bug, cdktf-cli, v0.1
