### ISSUE TITLE
Can't access clusterCaCertificate from ContainerCluster

### ISSUE THREAD

**Issue by Zubnix** [hashicorp/terraform-cdk#672] opened 2021-05-02 21:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Typescript 0.3.0

### Affected Resource(s)

provider-google
ContainerCluster

### Debug Output

`clusterCaCertificate` for use in `KubernetesProviderConfig` is not accessible from `ContainerCluster` object.

### Expected Behavior

Looking at https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/using_gke_with_terraform the 
`clusterCaCertificate` should be accessible via `my_cluster.master_auth[0].cluster_ca_certificate` however it is typed in such a way that the cluster_ca_certificate is not accessible.
```
export interface ContainerClusterMasterAuth {
  /** The password to use for HTTP basic authentication when accessing the Kubernetes master endpoint. */
  readonly password?: string;
  /** The username to use for HTTP basic authentication when accessing the Kubernetes master endpoint. If not present basic auth will be disabled. */
  readonly username?: string;
  /** client_certificate_config block */
  readonly clientCertificateConfig?: ContainerClusterMasterAuthClientCertificateConfig[];
}

export interface ContainerClusterMasterAuthClientCertificateConfig {
  /** Whether client certificate authorization is enabled for this cluster. */
  readonly issueClientCertificate: boolean;
}
```

### Actual Behavior

Can't create a `KubernetesProvider` from a `ContainerCluster`

### Steps to Reproduce

Create a `ContainerCluster`, try creating a working `KubernetesProvider`.

**Comment by jsteinich** [comment] 2021-05-03 02:51
I believe this to be another instance of #172.
https://github.com/hashicorp/terraform-cdk/issues/466 may be helpful for coming up with a workaround.

**Comment by skorfmann** [comment] 2021-05-03 08:02
Closing as duplicate of #172

**Closed by skorfmann** 2021-05-03 08:02 UTC
Labels: bug, duplicate, v0.0
