### ISSUE TITLE
Azure AppService Site config 

### ISSUE THREAD

**Issue by guan840912** [hashicorp/terraform-cdk#261] opened 2020-07-29 01:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

0.0.12

### Affected Resource(s)

AppService

### Debug Output

cdktf deploy --auto-approve
⠋ synthesizing ...
azure-app-service-docker
⠴ planning azure-app-service-docker...

Error: Extraneous JSON object property

  on cdk.tf.json line 95, in resource.azurerm_app_service.azureappservicedocker_dockercdktf_C07574BD.site_config[0]:
  95:             "use32_bit_worker_process": true

No argument or block type is named "use32_bit_worker_process". Did you mean
"use_32_bit_worker_process"?

non-zero exit code 1

### Expected Behavior

`use_32_bit_worker_process` in cdk.tf.json , but result is `use32_bit_worker_process` in cdk.tf.json .

### Actual Behavior
`use_32_bit_worker_process` in cdk.tf.json .

**Comment by skorfmann** [comment] 2020-07-29 20:15
Thanks for the bug report @guan840912 - I can confirm that's a bug, which will be tackled in https://github.com/hashicorp/terraform-cdk/issues/235 soon. Meanwhile, you can workaround this in similar fashion as described here https://github.com/hashicorp/terraform-cdk/issues/235#issuecomment-662942782

Can you confirm the workaround works for you?

**Comment by guan840912** [comment] 2020-08-01 00:53
thanks ~~~

**Comment by skorfmann** [comment] 2020-08-01 08:33
Closing as duplicate of #235

**Closed by skorfmann** 2020-08-01 08:33 UTC
Labels: bug, duplicate

**Comment by guan840912** [comment] 2020-08-01 13:08
Sorry ~~ , please reopen this issue @skorfmann .
thanks ~~~ > < 
when I upgrade to 0.0.13 , the bug still exist.
<img width="824" alt="截圖 2020-08-01 下午9 06 48" src="https://user-images.githubusercontent.com/46012524/89102347-ed246b00-d43a-11ea-8f40-71f177522ad2.png">

**Comment by skorfmann** [comment] 2020-08-03 14:42
> when I upgrade to 0.0.13 , the bug still exist.

@guan840912 sorry for the confusion. This wasn't part of of the `0.0.13` release, but it's going to be worked on soon. I closed it as a duplicate of issue #235 so we don't track the same thing in multiple places. Please subscribe to #235 in order to get notified when this gets merged to master / is released.
