### ISSUE TITLE
Error when doing cdktf deploy on github action

### ISSUE THREAD

**Issue by uryy2022** [hashicorp/terraform-cdk#2837] opened 2023-04-25 06:17 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- CDKTF `0.15.5` with Golang: `1.20.2` , Nodejs: `19.7.0`, Terraform: `1.2.9`
- AWS Provider `4.59.0`
- Datadog Provider `3.22.0`
### Affected Resource(s)

- Error after CDKTF deploy.
### Debug Output

- https://gist.github.com/uryy2022/bcdd29ec6544843a0886bd569b420d6a
### Expected Behavior
- The resource is to be deployed without error.

### Actual Behavior
- I can deploy the resource, but then I get a  `or: Unexpected token 'c', "[command]/h"... is not valid JSON` error.

### Steps to Reproduce
- Run the github action workflow in gist.
- The source code (main.go) contains code to create a Datadog resource using terraform-cdk-go.

### Important Factoids
- On github action, I can run `terraform apply` on the terraform resource output after `cdktf synth` without error.
- I can run `cdktf deploy --auto-approve` from my PC (Mac) in a similar environment without error.

### References

- https://gist.github.com/uryy2022/bcdd29ec6544843a0886bd569b420d6a

**Comment by ansgarm** [comment] 2023-06-23 08:29
Hi @uryy2022 👋

This seems like a duplicate of https://github.com/hashicorp/terraform-cdk/issues/1729

For a fix refer to: https://github.com/hashicorp/terraform-cdk/issues/1020

**Closed by ansgarm** 2023-06-23 08:29 UTC
Labels: bug, needs-priority
