### ISSUE TITLE
Terraform CDK does not allow output from one resource to be used in another resource

### ISSUE THREAD

**Issue by krish7919** [hashicorp/terraform-cdk#844] opened 2021-07-24 12:10 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
- Using v0.4.1
- Using CDK for Python

### Affected Resource(s)

[aws_db_proxy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_proxy)

Description of the problem:

I am spinning up and AWS RDS Proxy using cdktf which does not expose a resource ID. It is part of the ARN though which AWS exposes, and is part of the attribute of the resource in Terraform. For example, an ARN as `arn:aws:rds:eu-central-1:123456789:db-proxy:prx-1234567890` has the resource ID as `prx-1234567890`. This has been mentioned to AWS support and hopefully they will update this at their end, which can then be used to update the terraform-aws-provider.

Hence, I tried to use the `add_override` functionality to update the `arn` attribute to the resouce id by using:

```
rds_proxy = DbProxy(...)
rds_proxy.add_override("arn", 'element(split(":", ' + rds_proxy.arn + "),6)")
```

However, I get an error saying that the `arn` attribute cannot be modified: `Error: Value for unconfigurable attribute ... Can't configure a value for "arn": its value will be decided automatically`

So I tried adding a new attribute. This results in an error stating that I cannot add a new, unknown resource: `Error: Extraneous JSON object property... No argument or block type is named "resource_id".`

Next I tried adding an output in cdktf and then use that as input to the next resource as:

```
rds_proxy_resource_id = TerraformOutput(
            self, "rds_proxy_resource_id", value=rds_proxy.arn
        )
rds_proxy_resource_id.add_override(
            "value", 'element(split(":", ' + rds_proxy.arn + "),6)"
        )
...
...
(policy["Statement"][0]["Resource"]).append(
            "arn:aws:rds-db:eu-central-1:1234567890:dbuser:{}/rds_proxy_user".format(
                rds_proxy_resource_id.value,,
            )
        )
```

However, this does not work as the output is calculated at the end of the plan/apply cycle.

The end goal is the configre the IAM Auth for access to the RDS Proxy by adding an AWS IAM Policy as:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "rds-db:connect"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:rds-db:eu-central-1:123456789:dbuser:prx-123456789/rds_proxy_user"
        }
    ]
}
```

However, I always end up with the policy looking like: `"Resource": "arn:aws:rds-db:eu-central-1:123456789:dbuser:arn:aws:rds:eu-central-1:1234567890:db-proxy:prx-01234567897/rds_proxy_user"`.

I have given up on trying to massage the value in code after numerous attempts in CDK/Terraform somehow.
How does one perform higher-level operations on strings (and other values in general) when linking resources together in CDK Python?

**Comment by krish7919** [comment] 2021-07-24 12:50
I am also trying to figure out how to use a `data.external` resource in CDKTF which will help me offload all the logic to external script to do this.. Is there an example anywhere how to use `data.external` resource and call a script from cdk?

**Comment by jsteinich** [comment] 2021-07-24 16:19
The value that you are providing to your override is the right idea, but rather than provide to the proxy, you just need to use that directly when creating your iam policy. Something like:
```
iam_policy.resource = 'arn:aws:rds-db:eu-central-1:123456789:dbuser:${element(split(":", ' + rds_proxy.arn + "),6)}/rds_proxy_user"
```

I'm not aware of an examples using `data.external`. The general idea would be:

1. Add external provider to cdktf.json
2. Run cdktf get to generate provider bindings for it
3. Add import and start using in your app
4. Can use `.result('key')` to get add data from it

That said, you might consider just calling the script directly from your code.

**Comment by krish7919** [comment] 2021-07-24 17:33
I tried the suggestion to plug in the expression directly in the policy; it does not work:

```
...
Terraform has been successfully initialized!
Error: Invalid character
  on cdk.tf.json line 222, in resource.aws_iam_policy.rds_iam_auth:
 222:         "policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Action\": [\"rds-db:connect\"], \"Effect\": \"Allow\", \"Resource\": [\"arn:aws:rds-db:eu-central-1:1234567890:dbuser:${element(split(\\\":\\\", ${aws_db_proxy.rds-proxy-resource.arn}),6)}/rds_proxy_user\"]}]}",
This character is not used within the language.
```

**Comment by jsteinich** [comment] 2021-07-25 03:38
I believe the problem is with the arn reference. Try replacing `rds_proxy.arn` with `rds_proxy.fqn + ".arn),6...`

**Comment by krish7919** [comment] 2021-07-26 15:50
@jsteinich I am not able to understand what is wrong here; I tried your approach above:

```
...
...
Terraform has been successfully initialized!
Error: Invalid character
  on cdk.tf.json line 222, in resource.aws_iam_policy.rds_iam_auth:
 222:         "policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Action\": [\"rds-db:connect\"], \"Effect\": \"Allow\", \"Resource\": [\"arn:aws:rds-db:eu-central-1:1234567890:dbuser:${element(split(\\\":\\\", aws_db_proxy.aws-rds-proxy.arn),6)}/rds_proxy_user\"]}]}",
This character is not used within the language.
Error: Invalid expression
  on cdk.tf.json line 222, in resource.aws_iam_policy.rds_iam_auth:
 222:         "policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Action\": [\"rds-db:connect\"], \"Effect\": \"Allow\", \"Resource\": [\"arn:aws:rds-db:eu-central-1:1234567890:dbuser:${element(split(\\\":\\\", aws_db_proxy.aws-rds-proxy.arn),6)}/rds_proxy_user\"]}]}",
Expected the start of an expression, but found an invalid expression token.
```

**Comment by krish7919** [comment] 2021-07-26 19:02
I think I do not understand cdktf syntax at all, I tried a small test:

```
'arn:aws:rds-db:{}:{}:dbuser:${{format("%s", "this")}}/{}'.format(
                aws_region,
                aws_account_id,
                rds_proxy.fqn,
                username,
            )
```

And I get:

```
Terraform has been successfully initialized!
Error: Invalid character
  on cdk.tf.json line 222, in resource.aws_iam_policy.rds_iam_auth:
 222:         "policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Action\": [\"rds-db:connect\"], \"Effect\": \"Allow\", \"Resource\": [\"arn:aws:rds-db:eu-central-1:1234567890dbuser:${format(\\\"%s\\\", \\\"this\\\")}/aws_db_proxy.this\"]}]}",
This character is not used within the language.
Error: Invalid expression
  on cdk.tf.json line 222, in resource.aws_iam_policy.rds_iam_auth:
 222:         "policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Action\": [\"rds-db:connect\"], \"Effect\": \"Allow\", \"Resource\": [\"arn:aws:rds-db:eu-central-1:1234567890:dbuser:${format(\\\"%s\\\", \\\"this\\\")}/aws_db_proxy.this\"]}]}",
Expected the start of an expression, but found an invalid expression token.
```

**Comment by krish7919** [comment] 2021-07-26 20:44
Another attempt for the HCL parsing to work: I escape the `$` at the beginning of the `${element...` and it goes through fine with parsing, but then breaks at the policy rendering step.

Code:
```
'arn:aws:rds-db:{}:{}:dbuser:$${{element(split(":", {}.arn),6)}}/{}'.format(
                aws_region,
                aws_account_id,
                rds_proxy.fqn,
                "rds_proxy_user",
            )
```

Terraform diff:

```
- "arn:aws:rds-db:eu-central-1:123456789:dbuser:prx-01234567890/rds_proxy_user",
+ "arn:aws:rds-db:eu-central-1:123456789:dbuser:${element(split(\":\", aws_db_proxy.this.arn),6)}/rds_proxy_user",
```

Error:
```
...
aws_iam_policy.rds_iam_auth: Modifying...
...
Error: error updating IAM policy arn:aws:iam::123456789:policy/policies/aws-iampolicy-rdsiamauth: MalformedPolicyDocument: Syntax errors in policy.
	status code: 400, request id: XX-XX-XX-XX-XX
  on cdk.tf.json line 242, in resource.aws_iam_policy.rds_iam_auth:
 242:       }
```

**Comment by jsteinich** [comment] 2021-07-28 03:11
> I escape the `$` at the beginning of the `${element...` and it goes through fine with parsing

You don't want to escape the `$`. What you have in the diff is what we are shooting for existing in the synthesized cdktf.json file. Terraform will then know to execute what's contained in `${}` to get your end result.

Looking a bit closer at some of your previous outputs, it looks the the split separator is being escaped incorrectly.

**Comment by DanielMSchmidt** [comment] 2022-02-24 08:52
Closing this since the issue seems to be solved and we have no action on this issue for half a year :) Let me know if I shall reopen it 👍

**Closed by DanielMSchmidt** 2022-02-24 08:52 UTC
Labels: bug, question, language/python, waiting-on-answer, v0.4
