### ISSUE TITLE
CDKTF plan is running Terraform Init on every Run

### ISSUE THREAD

**Issue by sabinayakc** [hashicorp/terraform-cdk#2603] opened 2023-02-06 21:24 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

language: typescript
cdktf-cli: 0.15.2
node: v16.17.0
cdktf: null
constructs: 10.1.162
jsii: null
terraform: 1.3.7
arch: x64
os: linux 5.10.102.1-microsoft-standard-WSL2

### Affected Resource(s)

`cdktf plan`
`cdtkf apply`

### Expected Behavior
The plan should run `Terraform Init` only when providers or dependencies have changed. 

### Actual Behavior

The plan is running `Terraform Init` on every run even if nothing has changed in the code. A typical plan takes 2 to 3 minutes just to get to the "planning" stage and get the remote urls. Most of its time is spent on downloading and re-retrieving providers which are already in `.terraform` folder. 

### Steps to Reproduce

- Setup a cdktf typescript project
- Configure Terraform Cloud Workspace and Cloud Backend
- Run `cdktf plan` or `apply`

### Important Factoids

- When using API driven workflow (v0.14.3) this process is instant and a lot quicker. I get the remote URL pretty quick and the terraform init is not run every time. Even in the cloud. 
- I compared the API driven workflow (v0.14.3) vs CLI Driven (current version) and I am able to plan and apply a lot quicker.

**Comment by ansgarm** [comment] 2023-02-07 07:47
This seems to be a duplicate of #2525. Please try `0.15.3` which should fix this 👍

**Closed by ansgarm** 2023-02-07 07:47 UTC
Labels: bug, new
