### ISSUE TITLE
cdktf get in docker build fails with "TypeError: Cannot read properties of undefined (reading 'dots')"

### ISSUE THREAD

**Issue by nadworny** [hashicorp/terraform-cdk#1114] opened 2021-10-04 07:47 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf-cli@0.6.3-pre.360
node:16.10-alpine

### Affected Resource(s)
cdktf cli

### Debug Output
https://gist.github.com/nadworny/0d0c567efbbaeeab9e1169bab51811d6

### Expected Behavior
`cdktf get` works properly. It was actually working couple of days back with the same version of cdktf. I tried different versions of node:alpine but without success.

### Actual Behavior
Fails with the error.

### Steps to Reproduce
1. Clone the repo and go to `examples/python/docker`
2. Create a following Dockerfile:
```docker
FROM node:16.10-alpine

RUN npm install --global cdktf-cli@0.6.3-pre.360

ENV DEFAULT_TERRAFORM_VERSION=1.0.7

# Install Terraform
RUN apk add --update --no-cache git curl docker-cli unzip python3 python3-dev && \
    ln -sf python3 /usr/bin/python && python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools==45 && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    AVAILABLE_TERRAFORM_VERSIONS="0.15.0 ${DEFAULT_TERRAFORM_VERSION}" && \
    for VERSION in ${AVAILABLE_TERRAFORM_VERSIONS}; do curl -LOk https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip && \
    mkdir -p /usr/local/bin/tf/versions/${VERSION} && \
    unzip terraform_${VERSION}_linux_amd64.zip -d /usr/local/bin/tf/versions/${VERSION} && \
    ln -s /usr/local/bin/tf/versions/${VERSION}/terraform /usr/local/bin/terraform${VERSION};rm terraform_${VERSION}_linux_amd64.zip;done && \
    ln -s /usr/local/bin/tf/versions/${DEFAULT_TERRAFORM_VERSION}/terraform /usr/local/bin/terraform

WORKDIR /cdktf

# Prepare tf providers
COPY cdktf.json .
RUN cdktf get
```
3. Build image `docker build -t cdktf-test -f Dockerfile .`

**Comment by nadworny** [comment] 2021-10-04 07:53
Related to https://github.com/hashicorp/terraform-cdk/issues/1113. For my excuse - I searched in github issues for `TypeError` and didn't find that issue ;)

**Comment by DanielMSchmidt** [comment] 2021-10-04 09:26
I think this is a duplicate of #1113. It seems like Ink-Spinners have a broken and unpinned dependency. Thank you for the detailed reproduction steps! This is our top priority to fix, @ansgarm is already working on this

**Closed by DanielMSchmidt** 2021-10-04 09:26 UTC
Labels: bug, new

**Comment by ansgarm** [comment] 2021-10-04 13:41
Hi @nadworny, we've just release version `0.6.4` which should resolve the problem.
