### ISSUE TITLE
Documentation improvement concerning Terraform Element entity

### ISSUE THREAD

**Issue by danielBreitlauch** [hashicorp/terraform-cdk#1911] opened 2022-07-01 14:59 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to know more best practices concerning the TerrafromElement.
Is there a difference to Null Provider Resources?

It would be nice to have more documentation about this entity.
The Concepts page would be a perfect place.
https://www.terraform.io/cdktf/concepts/constructs

**Comment by jsteinich** [comment] 2022-07-02 19:50
Duplicate of #1910

**Closed by jsteinich** 2022-07-02 19:50 UTC
Labels: duplicate, enhancement, new
