### ISSUE TITLE
Wrong TF reference generated

### ISSUE THREAD

**Issue by DJAlPee** [hashicorp/terraform-cdk#352] opened 2020-08-27 10:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

package.json:
```json
  "dependencies": {
    "cdktf": "0.0.16",
    "constructs": "^3.0.4"
  },
  "devDependencies": {
    "@types/node": "^14.0.27",
    "cdktf-cli": "0.0.16",
    "typescript": "^3.9.7",
    "@types/aws-lambda": "^8.10.15"
  }
```
cdktf.json:
```json
{
  "language": "typescript",
  "app": "npm run --silent compile && node main.js",
  "terraformProviders": [
    "aws@~> 3.0"
  ]
}
```

running in CI/CD using docker image node:lts-alpine and downloading TF CLI 0.13.0 inside

### Affected Resource(s)

```ts
[...]

    const cert = new aws.AcmCertificate(this, 'cert', {
      domainName: `somedomain.example.com`,
      validationMethod: 'DNS',
      provider: globalProvider,
      lifecycle: {
        createBeforeDestroy: true
      }
    });

[...]

    const certValidation = new aws.AcmCertificateValidation(this, 'cert_validation', {
      dependsOn: [validationRecord],
      certificateArn: cert.arn,
      provider: globalProvider
    });

[...]

    const apiGatewayDomain = new aws.ApiGatewayDomainName(this, 'service_api_domain', {
      certificateArn: certValidation.certificateArn,
      domainName: `somedomain.example.com`,
      securityPolicy: 'TLS_1_2',
      endpointConfiguration: [{
        types: ['EDGE']
      }]
    });

[...]
```

### Important Factoids

When applying the config (cdktf deploy), I get following error:

```
Error: Error creating API Gateway Domain Name: BadRequestException: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidViewerCertificate; Request ID: xxxx-xxxx-xxxx-xxxx-xxxx; Proxy: null)

Error: Error creating Gateway base path mapping: Error creating Gateway base path mapping: NotFoundException: Invalid domain name identifier specified
```

After some investigations, I have seen, that the reference of the certificate in the generated cdk.tf.json comes directly from the cert resource `cert` and not from the cert validation resource `certValidation` as stated in the config (`certificateArn: certValidation.certificateArn`).
The actual ARN is the same, but when using the reference of the "wrong" resource, TF won't see the dependency and try to use the certificate before it's validated. When I apply the config again, it will work as expected.

As a workaround, I will add a `dependsOn` line to enforce the dependency.

### Expected Behavior

cdk.tf.json:
```json
   "aws_api_gateway_domain_name": {
      "app_serviceapidomain_88A6E49F": {
        "certificate_arn": "${aws_acm_certificate_validation.app_cert_validation_D8E49613.arn}", <-----------
        "domain_name": "somedomain.example.com",
        "security_policy": "TLS_1_2",
        "endpoint_configuration": [
          {
            "types": [
              "EDGE"
            ]
          }
        ],
        "//": {
          "metadata": { [...] }
        }
      }
    }
```

### Actual Behavior

cdk.tf.json:
```json
    "aws_api_gateway_domain_name": {
      "app_serviceapidomain_88A6E49F": {
        "certificate_arn": "${aws_acm_certificate.app_cert_D8E49613.arn}",    <-----------
        "domain_name": "somedomain.example.com",
        "security_policy": "TLS_1_2",
        "endpoint_configuration": [
          {
            "types": [
              "EDGE"
            ]
          }
        ],
        "//": {
          "metadata": { [...] }
        }
      }
    }
```

### Steps to Reproduce

npm install
npm run build
npm run synth

**Comment by jsteinich** [comment] 2020-08-27 12:34
I think this is a related issue to https://github.com/hashicorp/terraform-cdk/issues/188, since `certificateArn` is a required property of `AcmCertificateValidation`, the value that it was set to is being returned directly rather than a reference.

I think a workaround could look something like this:
```typescript
apiGatewayDomain.addOverride('certificate_arn', certValidation.getStringAttribute('arn'));
```

**Comment by DJAlPee** [comment] 2020-08-27 12:59
Yes, seems to be the same cause for this. Looking forward for the PR to be merged!

Your approach for a workaround is also quite nice...
Because I care more about the dependency, than the "value", the  explicit dependency using "dependsOn" is sufficient for me.

**Comment by skorfmann** [comment] 2020-09-06 09:11
Closing as duplicate of https://github.com/hashicorp/terraform-cdk/issues/188 and with a PR in the pipeline which is addressing this https://github.com/hashicorp/terraform-cdk/pull/310

**Closed by skorfmann** 2020-09-06 09:11 UTC
Labels: bug, duplicate
