### ISSUE TITLE
cdktf applications using docker provider don't generate valid Terraform JSON configuration

### ISSUE THREAD

**Issue by anubhavmishra** [hashicorp/terraform-cdk#303] opened 2020-08-11 23:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf-cli version 0.14

### Affected Resource(s)

docker provider

### Debug Output

```bash
cdktf deploy
⠏ initializing demo-cdktf-ts-docker...

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/docker -> terraform-providers/docker

If these suggestions look correct, upgrade your configuration with the
following command:
    terraform 0.13upgrade .

non-zero exit code 1
```

### Expected Behavior

The docker image is deployed.

The expected Terraform JSON that is valid is as follows:

```json
{
  "//": {
    "metadata": {
      "version": "0.0.0",
      "stackName": "demo-cdktf-ts-docker"
    }
  },
  "terraform": {
    "required_providers": {
      "docker": {
        "source": "terraform-providers/docker"
      }
    }
  },
.....
```

### Actual Behavior

The `cdktf get` command is successful and is able to generate TypeScript classes for the docker provider. The `cdktf deploy` command fails as the synthesized Terraform JSON configuration doesn't have the provider source specified in the `required_provider` block. Here is a snippet of the generated JSON:

```json
{
  "//": {
    "metadata": {
      "version": "0.0.0",
      "stackName": "demo-cdktf-ts-docker"
    }
  },
  "terraform": {
    "required_providers": {
      "docker": "~> 2.0"
    }
  },
  "provider": {
    "docker": [
      {}
    ]
  },
.....
```

### Steps to Reproduce

* Clone the hashicorp/terraform-cdk project
* Navigate to the examples/typescript/docker directory
* Run `cdktf get`
* Run `cdktf deploy`

### References

* #118

**Comment by skorfmann** [comment] 2020-08-12 04:58
```json
{
  "//": {
    "metadata": {
      "version": "0.0.0",
      "stackName": "demo-cdktf-ts-docker"
    }
  },
  "terraform": {
    "required_providers": {
      "docker": {
        "version": "~> 2.0",
        "source": "terraform-providers/docker"
      }
    }
  },
  "provider": {
    "docker": [
      {}
    ]
  },
```

That's for me on master.

![Screenshot 2020-08-12 at 06 56 21](https://user-images.githubusercontent.com/136789/89976588-1d54e080-dc69-11ea-8e4e-4da5c0fe5e80.png)

Could you double check which version is being used?

**Comment by skorfmann** [comment] 2020-08-12 18:06
Just tried it in a fresh project, works as well:

```json
  "//": {
    "metadata": {
      "version": "0.0.14",
      "stackName": "demo-cdktf-ts-docker"
    }
  },
  "terraform": {
    "required_providers": {
      "docker": {
        "version": "~> 2.0",
        "source": "terraform-providers/docker"
      }
    }
  },
  "provider": {
    "docker": [
      {}
    ]
  },
```

**Comment by Mejato** [comment] 2020-08-13 08:33
@skorfmann 
I managed to reproduce the issue when i upgraded my Terraform version from  0.12.29 to 0.13.0.

My provider is set to docker as below and everything works fine with version 0.12.29

{
  "language": "python",
  "app": "pipenv run ./main.py",
  "terraformProviders": ["docker"],
  "codeMakerOutput": "imports"
}

When i upgrade to version 0.13.0 i get this error.
⠸ downloading and generating providers...

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/docker -> terraform-providers/docker

If these suggestions look correct, upgrade your configuration with the
following command:
    terraform 0.13upgrade .

Then when i change my provider to the following i cant seem to import any modules from the imports directory anymore.
{
  "language": "python",
  "app": "pipenv run ./main.py",
  "terraformProviders": ["terraform-providers/docker"],
  "codeMakerOutput": "imports"
}

**Comment by skorfmann** [comment] 2020-08-13 08:37
@Mejato There are probably two issues:

- Please make sure to upgrade the `cdktf` package as well. That's not obvious at the moment. I'll create another issue to address this.
- after upgrading and changing the `cdktf.json` configuration, please run `cdktf get` again

**Comment by Mejato** [comment] 2020-08-13 08:41
@skorfmann 
I forgot to mention it, but my cdktf version is 0.0.14 when above happens.

**Comment by skorfmann** [comment] 2020-08-13 08:42
> I forgot to mention it, but my cdktf version is 0.0.14 when above happens.

Did you run a `cdktf get` afterwards?

**Comment by Mejato** [comment] 2020-08-13 08:57
Yes and thats when i get the following error

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

hashicorp/docker -> terraform-providers/docker

If these suggestions look correct, upgrade your configuration with the
following command:
terraform 0.13upgrade .

**Comment by skorfmann** [comment] 2020-08-13 08:59
Could you publish this as a repo somewhere, so I can have a look?

**Comment by Mejato** [comment] 2020-08-13 09:07
https://github.com/Mejato/Terraform_Docker_Provider.git

**Comment by skorfmann** [comment] 2020-08-13 09:23
> https://github.com/Mejato/Terraform_Docker_Provider.git

For the `cdktf get` to work, this file has to be adjusted https://github.com/Mejato/Terraform_Docker_Provider/blob/559e076af19746e6bcc1848cc3459775f0c18b5f/Docker/Getting_Started/cdktf.json#L4


```json
{
  "language": "python",
  "app": "pipenv run ./main.py",
  "terraformProviders": ["terraform-providers/docker"],
  "codeMakerOutput": "imports"
}
```

What I believe you did and probably got lost while publishing. One issue I saw for me locally though:  The generated python package is:

- empty
- a different path than expected 

I'll have more thorough look later today.

**Comment by Mejato** [comment] 2020-08-13 09:30
It only happens with the docker provider and when using the 'terraform-providers/docker' provider with Terraform version 0.13.0 the provider modules doesn't load from the imports directory and my project folder is marked as sources root and acknowledges the package imports.terraform-providers.

I can also confirm that another provider works running Terraform version 0.13.0.
`{
  "language": "python",
  "app": "pipenv run ./main.py",
  "terraformProviders": ["azurerm@~> 2.0"],
  "codeMakerOutput": "imports"
}`

**Comment by skorfmann** [comment] 2020-08-13 13:52
In some cases, it looks like that existing state has to adapted as well - see https://github.com/hashicorp/terraform/issues/25794#issuecomment-673111674

Just had to this for an existing project when upgrading to `0.13.0`

```
cd cdktf.out
terraform state replace-provider -state ../terraform.tfstate 'registry.terraform.io/-/aws' 'registry.terraform.io/hashicorp/aws'
```

**Comment by skorfmann** [comment] 2020-08-13 21:08
@Mejato thanks again for uploading your example, this helped me to understand the issue. While Typescript was working fine, the Python workflow was broken for providers which aren't maintained by HashiCorp (and hence have a namespace in 0.13). 

It'll be fixed with #309

**Comment by Mejato** [comment] 2020-08-13 21:47
@skorfmann , awesome thanks for your assistance!

**Comment by skorfmann** [comment] 2020-08-25 09:42
Closing as https://github.com/hashicorp/terraform-cdk/pull/309 was merged and released

**Closed by skorfmann** 2020-08-25 09:42 UTC
Labels: bug, providers
