### ISSUE TITLE
0.0.19 nested CamelCase attributes not being converted to snake_case, breaks AWS provider

### ISSUE THREAD

**Issue by JohnCalhoun** [hashicorp/terraform-cdk#468] opened 2020-12-22 20:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Typescript
cdktf: 0.0.19

### Affected Resource(s)

at least most of the AWS resources

### Expected Behavior

nested CamelCase attributes (required by the types from the AWS provider) should be converted to snake_case

### Actual Behavior

conversion does not happen

### Steps to Reproduce

try and create any resources that has nested objects, for example a dynamodb table with secondary indexs

### References

* #0000

**Comment by jsteinich** [comment] 2020-12-23 15:15
I just ran a test and attributes were converted correctly.

Did you recently update from an earlier version of cdktf? If so, you'll need to make sure to run `cdktf get` to update the generated provider code. Also make sure both `cdktf` and `cdktf-cli` packages are on the same version.

**Comment by skorfmann** [comment] 2021-01-08 15:31
@JohnCalhoun is this still relevant?

**Comment by ajwood-acquia** [comment] 2021-01-14 20:16
this issue is causing me trouble currently. I'm hoping for a resolution.

**Comment by ajwood-acquia** [comment] 2021-01-15 20:52
This issue is affecting me as well. I've done as @jsteinich suggested and ran `cdktf get`, and I've confirmed that `cdktf` and `cdktf-cli` are on the same version.
This issue is impacting me on both 0.0.19 and 0.1.0. Rolling back both the library and the CLI to 0.0.18 seems to work around the issue, but it reappears on updating to the latest version.

**Comment by jsteinich** [comment] 2021-01-16 14:01
@ajwood-acquia can you post a snippet from a resource that is having issues? Also the providers section of `cdktf.json`. Which language are you using?

**Comment by ajwood-acquia** [comment] 2021-01-19 16:13
Here's a resource with the issue. This was generated using `cdktf` and `cdktf-cli` 0.1.0:
```
  "resource": {
    "signalfx_dashboard_group": {
      <...>
      "dashboardingautomation_successratecountDevOpsSuccessRateByCountDevOpspipelinetestingboard_C2249A73": {
        "axes_include_zero": true,
        "description": "Success Rate (14d rolling window) : ",
        "name": "Success Rate By Count",
        "program_text": "total_tasks = data('test_data.gauge.exponential_dist.scale_20.shift_4.ts_lag_gamma', rollup='sum',extrapolation='last_value', maxExtrapolations=3).publish(label='Total Tasks', enable=False)\nsuccessful_tasks = data('test_data.gauge.gaussian_dist.discretized_3.scale_2.shift_-1', rollup='sum',extrapolation='zero', maxExtrapolations=3).publish(label='Successful Tasks', enable=False)\nresult = (100*successful_tasks/total_tasks).mean(over='14d').sum().publish(label='Success Rate', enable=True)",
        "axis_left": [
          {
            "label": "Percent",
            "maxValue": 100,
            "minValue": 0
          }
        ],
        "viz_options": [
          {
            "label": "Success Rate",
            "valueSuffix": "%"
          }
        ],
        "//": {
          "metadata": {
            "path": "dashboarding-automation/success_rate_countDevOpsSuccess Rate By CountDevOps pipeline testing board",
            "uniqueId": "dashboardingautomation_successratecountDevOpsSuccessRateByCountDevOpspipelinetestingboard_C2249A73",
            "stackTrace": [
              <redacted>
            ]
          }
        }
      },
      <...>
    }
  }
```
The issue is with dictionary keys in `obj[resource][signalfx_dashboard_group][dashboarding_...][axis_left]` - `minValue` and `maxValue` are rejected as being incorrectly cased when we try to deploy this tf.out file.

Here's our providers section:
```
  "provider": {
    "vault": [
      {
        "address": "http://127.0.0.1:8200"
      }
    ],
    "signalfx": [
      {
        "auth_token": "${data.vault_generic_secret.<redacted>}"
      }
    ]
  },
```

We're using Python for this project.

**Comment by jsteinich** [comment] 2021-01-20 03:48
@ajwood-acquia what does your python code look like for that resource? I just ran a simple test using the following without issue.
```python
        TimeChart(self, "chart", 
            name="Success Rate By Count",
            program_text="text",
            axis_left=[
                TimeChartAxisLeft(label="Percent", max_value=100, min_value=0)
            ]
        )
```

**Comment by ajwood-acquia** [comment] 2021-01-20 15:41
```
    def create_charts(self):
        chart = TimeChart(self.app,
                          id='resource_accumulation_trend' + self.id_postfix,
                          name=self.chart_name,
                          program_text=self.signalflow_program,
                          description='Shows total quantity accumulated per time slice : ' + self.chart.description,
                          axes_include_zero=True,
                          viz_options=[TimeChartVizOptions(label='Resource Sum')],
                          axis_left=[TimeChartAxisLeft(label=(self.format_unit_for_label()))]
                          )
        self.chart_ids.append(chart.id)
```

**Comment by jsteinich** [comment] 2021-01-21 14:29
I can't help but think that stale generated code is at play here.
@ajwood-acquia can you open up the zip file (`imports/signalfx/_jsii/signalfx@0.0.0.jsii.tgz`) and find the contents of `package/providers/signalfx/time-chart.js`? In particular I'm looking to see if it has a function named `timeChartAxisLeftToTerraform`.

**Comment by ajwood-acquia** [comment] 2021-01-21 19:38
No such string exists in that file

**Comment by jsteinich** [comment] 2021-01-21 23:37
> No such string exists in that file

That does mean the generated provider is stale. Can you please try the upgrade again? Make sure to install a new version of cdktf and then run `cdktf get` to regenerate code.

**Comment by ajwood-acquia** [comment] 2021-01-22 21:01
That was the trick! I must not have rerun the get after changing versions...
Thanks for your help! Sorry for the false report ^_^;

**Comment by jsteinich** [comment] 2021-01-23 00:03
No worries. Glad it's working for you now.

I think there's room for improved documentation on how to upgrade (0.0.18 to 0.0.19 was a big change).

**Comment by skorfmann** [comment] 2021-01-27 10:16
> I think there's room for improved documentation on how to upgrade (0.0.18 to 0.0.19 was a big change).

You mean in documentation around upgrading in general?

**Comment by jsteinich** [comment] 2021-01-27 13:43
> > I think there's room for improved documentation on how to upgrade (0.0.18 to 0.0.19 was a big change).
> 
> You mean in documentation around upgrading in general?

Opened #526 to continue the topic of documentation.

**Comment by skorfmann** [comment] 2021-02-01 14:07
Closing since original issue seems to be solved and a follow up for docs was created. Thanks for you help @jsteinich

**Closed by skorfmann** 2021-02-01 14:07 UTC
Labels: waiting-on-answer
