### ISSUE TITLE
provider-azurerm: add vmSize definition with predefined constant for provider-azurerm

### ISSUE THREAD

**Issue by lazzyms** [hashicorp/terraform-cdk#3059] opened 2023-08-09 12:27 UTC
### Description

Add a constant and typedef for `vmSize` parameter with predefined values for vm size in azure and updating the type of `vmSize` parameter to the typedef instead of `string`

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment] 2023-08-11 08:16
Hey, the information if a string is actually an enum (a data type that does not exist in Terraform HCL) is only represented in the documentation and the code of the provider. Because of that it is impossible for our code generation process to pick this up and generate an enum without an enormous effort (e.g. scraping the documentation pages for this information). We would really love to have this feature as well, but in the meantime I would suggest creating a construct inheriting from the resource you want to use and add this typing on a case by case basis, e.g. in Typescript:

```ts
type VmSize = "small" | "medium" | "large";

type BetterVmInstanceConfig = Omit<VmInstanceConfig, "size"> & { size:  VmSize };
class BetterVmInstance extends VmInstance {
  constructor(scope: Construct, name: string, config: BetterVmInstanceConfig) {
    super(scope, name, config);
  }
}
```

**Comment by xiehan** [comment] 2023-08-11 09:43
Closing as a duplicate of #2945.

**Closed by xiehan** 2023-08-11 09:43 UTC
Labels: duplicate, enhancement, priority/backlog, provider get / generation, ux/configuration, size/large
