### ISSUE TITLE
AWS_PROVIDER: Pre-built provider is not picking up new provider versions (>5.0)

### ISSUE THREAD

**Issue by rirze** [hashicorp/terraform-cdk#2923] opened 2023-06-08 14:43 UTC
### Expected Behavior

We should have a `cdktf_cdktf_provider_aws` library that is running on 5.1.0. It's been over a month since the last cdktf-aws provider library has been built and Terraform's AWS provider has released 3 versions since then. 

### Actual Behavior

Library cannot run on latest provider.

### Steps to Reproduce

look at https://github.com/cdktf/cdktf-provider-aws and compare to https://github.com/hashicorp/terraform-provider-aws/releases

### Versions

latest.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiehan** [comment] 2023-06-09 09:20
I'm closing this as a duplicate of #2879 and #2897 since we are already tracking this issue. We've been running into various build and memory issues as well as struggling with a new resource added to the AWS provider in 4.67 that's causing problems. We've been treating this as a SEV1 internally and working hard to get a fix out, but it's not proving as simple as we'd hoped. Our priority is to get a working build of 4.67 (#2879) out first for those folks who aren't ready to upgrade to 5.x yet, and then we'll work on getting the 5.x versions added (#2897).

**Closed by xiehan** 2023-06-09 09:20 UTC
Labels: bug, duplicate, pre-built providers
