### ISSUE TITLE
COMPONENT: CDKTF Upgrade Documentation

### ISSUE THREAD

**Issue by sabinayakc** [hashicorp/terraform-cdk#3125] opened 2023-09-07 14:47 UTC
### Description

When upgrading cdktf project and providers to latest version using `package.json`, 

It is necessary to run `terraform init --upgrade` by going inside the `cdktf.out/stacks/my-stack` folder otherwise terraform will complain (especially if using terraform cloud) since the `.terraform.lock.hcl` file references old values. 

Is this an expected behaviour or something we should document? 
OR
Should `cdktf cli` take care of updating the `.terraform.lock.hcl` or running similar actions?
OR
I need to also modify my `cdtkf.json` with newer versions?
OR 
Am I missing something? 

Thank you. 

<img width="422" alt="image" src="https://github.com/hashicorp/terraform-cdk/assets/13154166/35accf88-222c-46b5-b17a-1775aa5b9709">

### Links

https://developer.hashicorp.com/terraform/cdktf/release/upgrade-guide-v0-18

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiehan** [comment] 2023-09-18 07:45
This is a duplicate of #526 - please upvote that issue instead!

**Closed by xiehan** 2023-09-18 07:45 UTC
Labels: documentation, duplicate
