### ISSUE TITLE
CDKTF convert crashes on importing HCL files

### ISSUE THREAD

**Issue by dbryson-solo** [hashicorp/terraform-cdk#2834] opened 2023-04-24 16:41 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDKTF `0.16.0`
AWS Provider: `hashicorp/aws@ ~> 4.0`

### Affected Resource(s)

CDKTF generated resources.  Also this doesn't seem specific to python, performing this step with any output language causes this backtrace.

### Debug Output

(https://gist.github.com/dbryson-solo/79473107f1aeb9bb9b520211f98f426d)

### Expected Behavior

Python code should be generated.

### Actual Behavior

Node.js seems to crash when called by CDKTF.

```Error: Internal Error: unexpected array```

### Steps to Reproduce

Using the following file:
```
resource "aws_dynamodb_table" "accounts_v0" {
  attribute {
    name = "account_id"
    type = "S"
  }

  attribute {
    name = "item_id"
    type = "S"
  }

  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "item_id"
  name         = "accounts_v0"
  point_in_time_recovery {
    enabled = false
  }

  range_key = "account_id"
  ttl {
    attribute_name = ""
  }
}
```
Import with:
```
cdktf convert --language python --provider 'hashicorp/aws@ ~> 4.0'
```

### References

- #0000

**Comment by mutahhir** [comment] 2023-04-26 12:38
👋🏽 thanks for the issue. I was unable to reproduce the crash, however. 

```
echo 'resource "aws_dynamodb_table" "accounts_v0" {
  attribute {
    name = "account_id"
    type = "S"
  }

  attribute {
    name = "item_id"
    type = "S"
  }

  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "item_id"
  name         = "accounts_v0"
  point_in_time_recovery {
    enabled = false
  }

  range_key = "account_id"
  ttl {
    attribute_name = ""
  }
}' | cdktf convert --language python --provider 'hashicorp/aws@ ~> 4.0'
The 'npm view' command generated an error stream with content [npm WARN Ignoring workspaces for specified package(s)]
import constructs as constructs
# Provider bindings are generated by running cdktf get.
# See https://cdk.tf/provider-generation for more details.
import ...gen.providers.aws as aws
class MyConvertedCode(constructs.Construct):
    def __init__(self, scope, name):
        super().__init__(scope, name)
        aws.dynamodb_table.DynamodbTable(self, "accounts_v0",
            attribute=[{
                "name": "account_id",
                "type": "S"
            }, {
                "name": "item_id",
                "type": "S"
            }
            ],
            billing_mode="PAY_PER_REQUEST",
            hash_key="item_id",
            name="accounts_v0",
            point_in_time_recovery={
                "enabled": False
            },
            range_key="account_id",
            ttl={
                "attribute_name": ""
            }
        )
        ```
 Perhaps there was something else that was causing the error?

**Comment by mutahhir** [comment] 2023-07-14 10:48
```python
from constructs import Construct
#
# Provider bindings are generated by running `cdktf get`.
# See https://cdk.tf/provider-generation for more details.
#
from imports.aws.dynamodb_table import DynamodbTable
class MyConvertedCode(Construct):
    def __init__(self, scope, name):
        super().__init__(scope, name)
        DynamodbTable(self, "accounts_v0",
            attribute=[DynamodbTableAttribute(
                name="account_id",
                type="S"
            ), DynamodbTableAttribute(
                name="item_id",
                type="S"
            )
            ],
            billing_mode="PAY_PER_REQUEST",
            hash_key="item_id",
            name="accounts_v0",
            point_in_time_recovery=DynamodbTablePointInTimeRecovery(
                enabled=False
            ),
            range_key="account_id",
            ttl=DynamodbTableTtl(
                attribute_name=""
            )
        )
```

This issue should be resolved now on main. Will be included in the upcoming release.

**Closed by mutahhir** 2023-07-14 10:48 UTC
Labels: bug, priority/important-soon, feature/convert
