### ISSUE TITLE
Error Using cdk init --from-terraform-project on public module

### ISSUE THREAD

**Issue by maeghan-porter** [hashicorp/terraform-cdk#2609] opened 2023-02-07 23:12 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```% cdktf --version
0.15.3
```

### Affected Resource(s)

```
cdktf init --from-terraform-project
```

### Debug Output

https://gist.github.com/maeghan-porter/a8569aa5a72c96ddae92d27be03b60d8

### Expected Behavior

Outputted typescript of converted hcl.

### Actual Behavior

Linked error. No other output.

### Steps to Reproduce

I am trying to convert a cloudposse terraform module to cdktf as a starting point as we'd like to manage the resources ourself instead of using their module. So to reproduce, fork https://github.com/cloudposse/terraform-aws-eks-node-group and run `cdk init --from-terraform-project` against it.

**Comment by intothevoid1986** [comment] 2023-02-21 09:27
Same problem here with CDKTF 0.15.5 and AWS terraform project

**Comment by ansgarm** [comment] 2023-02-21 10:11
Hi 👋

Thank you for reporting this, it seems to be a duplicate of #2423 – so, I'm going to close this in favor of the other issue.

**Closed by ansgarm** 2023-02-21 10:11 UTC
Labels: bug, new
